import React,{useEffect,useRef,useState,type FormEvent} from 'react';
import {api} from './api';
import {PageError} from './ConnectionPages';
import type {Archive,BoundMember} from '../server/archives';
import {statesFor,isClosedState,isWorkState,memberLabel} from '../shared/archive-states';

export function MemberPicker({value,onChange,label}:{value:BoundMember[];onChange:(items:BoundMember[])=>void;label:string}){
 const[query,setQuery]=useState(''),[items,setItems]=useState<BoundMember[]>([]),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);const serial=useRef(0);
 async function load(before?:string){const n=++serial.current;setLoading(true);setError('');try{const r=await api<{members:BoundMember[];next_cursor:string|null}>('/members?'+new URLSearchParams({query,...(before?{before}:{})}));if(n!==serial.current)return;setItems(old=>before?[...old,...r.members]:r.members);setCursor(r.next_cursor);}catch(e){if(n===serial.current)setError((e as Error).message);}finally{if(n===serial.current)setLoading(false);}}
 useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>{clearTimeout(timer);serial.current++;};},[query]);
 return <div className="archive-member-picker"><p className="picker-label">{label}</p><div className="selected-members">{value.map(m=><span key={m.id}>{m.name}{m.frozen&&<small>已冻结</small>}<button type="button" aria-label={`移除${m.name}`} onClick={()=>onChange(value.filter(v=>v.id!==m.id))}>×</button></span>)}</div><details><summary>{value.length?`已选择 ${value.length} 人，调整成员`:'选择成员，可多选'}<span aria-hidden="true">⌄</span></summary><div className="member-picker-options"><input aria-label="搜索成员姓名" placeholder="搜索成员姓名" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><PageError error={error} retry={()=>void load()}/><div className="member-picker-results">{items.map(m=>{const checked=value.some(v=>v.id===m.id);return <label key={m.id}><input type="checkbox" checked={checked} disabled={m.frozen&&!checked} onChange={()=>onChange(checked?value.filter(v=>v.id!==m.id):[...value,m])}/><span>{m.name}{m.frozen&&<small>已冻结，不可新分配</small>}</span></label>;})}</div>{loading?<p role="status">正在查询成员…</p>:cursor?<button className="button quiet" type="button" onClick={()=>void load(cursor)}>更多成员</button>:!items.length&&<p>没有匹配成员</p>}</div></details></div>;
}
export function StateFields({type,status,onStatus,members,onMembers,reopen=false}:{type:'person'|'org';status:string;onStatus:(s:string)=>void;members:BoundMember[];onMembers:(m:BoundMember[])=>void;reopen?:boolean}){
 return <section className="archive-state-fields"><label>业务状态<select value={status} onChange={e=>onStatus(e.target.value)}>{statesFor(type).filter(s=>!reopen||!isClosedState(s)).map(s=><option key={s}>{s}</option>)}</select></label><MemberPicker label={memberLabel(type,status)+(isWorkState(type,status)?' · 至少一人':' · 可选')} value={members} onChange={onMembers}/>{isWorkState(type,status)&&members.length===0&&<p className="responsible-hint">请明确选择至少一名负责成员。</p>}{isClosedState(status)&&<p className="archive-readonly">保存后会关闭档案，基础资料与观察内容将变为只读。</p>}</section>;
}
export function ArchiveStateForm({archive,busy,setBusy,onSaved,onReload}:{archive:Archive;busy:boolean;setBusy:(b:boolean)=>void;onSaved:(id:string,changed:boolean)=>Promise<void>;onReload:()=>Promise<void>}){
 const initialStatus=archive.closed?archive.last_open_status??'视奸观察':archive.status;
 const[status,setStatus]=useState(initialStatus),[members,setMembers]=useState(archive.bindings[initialStatus]??[]),[error,setError]=useState(''),[requestId]=useState(()=>crypto.randomUUID());
 function choose(s:string){setStatus(s);setMembers(isClosedState(s)?archive.members:archive.bindings[s]??[]);}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<{id:string;changed:boolean}>(archive.closed?'/archives/reopen':'/archives/state',{id:archive.id,expected_version:archive.version,status,member_ids:members.map(m=>m.id),request_id:requestId});await onSaved(r.id,r.changed);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="manage-form" onSubmit={submit}><p className="secondary-copy">{archive.name}</p><StateFields type={archive.type} status={status} onStatus={choose} members={members} onMembers={setMembers} reopen={archive.closed}/><PageError error={error} retry={()=>void onReload().catch(e=>setError(e.message))} retryLabel="重新读取并替换表单"/><div className="dialog-actions"><button className={'button primary '+(isClosedState(status)?'close-archive-button':'')} disabled={busy||(isWorkState(archive.type,status)&&members.length===0)}>{busy?'正在保存…':archive.closed?'重新开启档案':isClosedState(status)?'保存并关闭档案':'保存状态与成员'}</button></div></form>;
}
