import {Highlight} from './Reading';
import {statesFor} from '../shared/archive-states';
import type {ObservationFocus} from './ObservationSection';
import {AvatarEditor,avatarUrl} from './AvatarEditor';
import React,{useEffect,useRef,useState,type FormEvent} from 'react';
import {api,type Member} from './api';
import {Avatar} from './Avatar';
import {Modal} from './Modal';
import {PageError} from './ConnectionPages';
import type {Archive,BoundMember} from '../server/archives';
import {ArchiveStateForm,StateFields} from './ArchiveStateForm';
import {isWorkState,memberLabel} from '../shared/archive-states';
import './archives.css';
import {TagsSection,TagSummary} from './TagsSection';
import {ObservationSection} from './ObservationSection';

type Kind='person'|'org';
type Preference={query:string;selected:string|null;scope:'all'|'mine'|'unread';status:string;member_id:string;closed:'all'|'open'|'closed'};
const defaults:Preference={query:'',selected:null,scope:'all',status:'',member_id:'',closed:'all'};
type ListArchive=Archive&{unread_count?:number;search_match?:{observation_id:string;excerpt:string}|null};
function preferences(key:string):Preference{try{return {...defaults,...JSON.parse(localStorage.getItem(key)??'{}')};}catch{return {...defaults};}}
const date=(value:string)=>new Date(value).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
export function ArchivesPage({actor,type,linked,detailOnly=false}:{actor:Member;type:Kind;linked?:{archiveId:string;focus:ObservationFocus};detailOnly?:boolean}){
 const prefKey=`cts:${actor.id}:${type}:archives`,[pref,setPref]=useState(()=>{const saved=preferences(prefKey),linked=new URLSearchParams(location.search).get('archive');return linked&&/^[0-9a-f-]{36}$/i.test(linked)?{...saved,selected:linked}:saved;});
 const[query,setQuery]=useState(pref.query),[items,setItems]=useState<ListArchive[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
 const[dialog,setDialog]=useState<'create'|Archive|null>(null),[stateDialog,setStateDialog]=useState<Archive|null>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Archive|null>(null),[draftIds,setDraftIds]=useState<string[]>([]);
 const request=useRef(0),label=type==='person'?'人物':'组织';
 const[focus,setFocus]=useState<ObservationFocus|undefined>(()=>{const p=new URLSearchParams(location.search);return p.has('event')||p.has('observation')?{event_id:p.get('event')??undefined,observation_id:p.get('observation')??undefined,query:p.get('highlight')??undefined,key:location.search}:undefined;}),[directory,setDirectory]=useState<BoundMember[]>([]),[directoryError,setDirectoryError]=useState(''),[directoryRetry,setDirectoryRetry]=useState(0);
 useEffect(()=>{if(linked){setPref(p=>({...p,selected:linked.archiveId}));setFocus(linked.focus);}},[linked?.archiveId,linked?.focus.key]);
 useEffect(()=>{let cancelled=false;setDirectoryError('');void (async()=>{let before:string|null=null,all:BoundMember[]=[];do{const r: {members:BoundMember[];next_cursor:string|null}=await api('/members?'+new URLSearchParams({limit:'100',...(before?{before}:{})}));all.push(...r.members);before=r.next_cursor;}while(before&&!cancelled);if(!cancelled)setDirectory(all);})().catch(e=>{if(!cancelled)setDirectoryError('成员筛选暂不可用：'+e.message);});return()=>{cancelled=true;};},[directoryRetry]);
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const changed=()=>{clearTimeout(timer);timer=setTimeout(()=>setRevision(n=>n+1),750);};window.addEventListener('cts-reading-confirmed',changed);window.addEventListener('cts-reading-stale',changed);return()=>{clearTimeout(timer);window.removeEventListener('cts-reading-confirmed',changed);window.removeEventListener('cts-reading-stale',changed);};},[]);
 useEffect(()=>{try{localStorage.setItem(prefKey,JSON.stringify(pref));}catch{/* Current-page preferences still work without storage. */}},[prefKey,pref]);
 useEffect(()=>{const timer=setTimeout(()=>setPref(p=>({...p,query})),250);return()=>clearTimeout(timer);},[query]);
 async function load(before?:string){
  const sequence=++request.current;setLoading(true);setError('');
  try{const r=await api<{archives:ListArchive[];next_cursor:string|null}>('/archives?'+new URLSearchParams({type,query:pref.query,scope:pref.scope,status:pref.status,member_id:pref.member_id,closed:pref.closed,...(before?{before}:{})}));if(sequence!==request.current)return;setItems(old=>before?[...old,...r.archives]:r.archives);setCursor(r.next_cursor);}catch(e){if(sequence===request.current)setError((e as Error).message);}finally{if(sequence===request.current)setLoading(false);}
 }
 useEffect(()=>{if(!detailOnly)void load();return()=>{request.current++;};},[type,pref.query,pref.scope,pref.status,pref.member_id,pref.closed,revision,detailOnly]);
 function choose(id:string|null,match?:ListArchive['search_match']){if(pref.selected!==id)setSelected(null);setPref(p=>({...p,selected:id}));const next=match?{observation_id:match.observation_id,query:pref.query,key:crypto.randomUUID()}:undefined;setFocus(next);if(!detailOnly){const params=new URLSearchParams();if(id)params.set('archive',id);if(next){params.set('observation',next.observation_id);params.set('highlight',next.query);}history.replaceState(null,'',location.pathname+(params.size?'?'+params:''));}}
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>|undefined;const refresh=()=>{clearTimeout(timer);timer=setTimeout(()=>{api<{drafts:{archive_id:string}[]}>('/drafts').then(r=>setDraftIds(r.drafts.map(d=>d.archive_id))).catch(()=>{});},500);};refresh();window.addEventListener('cts-drafts-changed',refresh);return()=>{clearTimeout(timer);window.removeEventListener('cts-drafts-changed',refresh);};},[]);
 async function saved(id:string,changed:boolean,message?:string){setDialog(null);setStateDialog(null);choose(id);setRevision(v=>v+1);setNotice(message??(changed?'档案已保存':'资料没有变化'));}
 return <main className={'archives-workspace '+(detailOnly?'detail-only ':'')+(pref.selected?'has-selection':'')}>
  <section className="archives-list-panel" aria-label={`${label}档案列表`}>
   <div className="archive-head"><h1>{label}档案</h1><div className="archives-search"><input aria-label="搜索档案" placeholder="搜索名称、联系方式、观察正文" value={query} maxLength={200} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}>×</button>}</div><button className="button primary" onClick={()=>setDialog('create')}>＋ 新建</button></div>
   <div className="archive-scope" aria-label="档案范围">{([['all','全部'],['mine','我负责'],['unread','有未读']] as const).map(([v,label])=><button key={v} aria-pressed={pref.scope===v} onClick={()=>setPref(p=>({...p,scope:v}))}>{label}</button>)}</div>
   <details className="archive-filters"><summary>组合筛选{(pref.status||pref.member_id||pref.closed!=='all')?' · 已启用':''}</summary><label>业务状态<select value={pref.status} onChange={e=>setPref(p=>({...p,status:e.target.value}))}><option value="">全部状态</option>{statesFor(type).map(v=><option key={v}>{v}</option>)}</select></label><PageError error={directoryError} retry={()=>setDirectoryRetry(n=>n+1)}/><label>当前关联成员<select value={pref.member_id} onChange={e=>setPref(p=>({...p,member_id:e.target.value}))}><option value="">全部成员</option>{directory.map(m=><option value={m.id} key={m.id}>{m.name}{m.frozen?'（冻结）':''}</option>)}</select></label><label>开启/关闭<select value={pref.closed} onChange={e=>setPref(p=>({...p,closed:e.target.value as Preference['closed']}))}><option value="all">全部</option><option value="open">开启</option><option value="closed">关闭</option></select></label></details>
   {(query||pref.scope!=='all'||pref.status||pref.member_id||pref.closed!=='all')&&<button className="button quiet" onClick={()=>{setQuery('');setPref(p=>({...defaults,selected:p.selected}));}}>清除搜索与筛选</button>}
   <div className="archives-caption"><span>{items.length} 个档案{cursor?' · 可继续加载':''}</span><span>最近更新 ↓</span></div>
   <PageError error={error} retry={()=>void load()}/>
   <div className="archives-rows">{items.map(a=><button key={a.id} className={'archive-row '+(pref.selected===a.id?'selected':'')} onClick={()=>choose(a.id,a.search_match)} aria-label={`查看${a.name}`}><Avatar name={a.name} type={a.type} src={avatarUrl('archive',a.id,a.version)}/><div className="archive-row-content"><div className="archive-row-title"><h2><Highlight text={a.name} query={pref.query}/></h2>{!!a.unread_count&&<span className="unread-badge">{a.unread_count} 未读</span>}</div><div className="archive-current"><span className={'state-badge small '+(a.closed?'closed':'')}>{a.status}</span><span className="archive-assignees"><span>{isWorkState(a.type,a.status)?'负责人':'关联'}</span> {a.members.length?a.members.map(m=>m.name+(m.frozen?'（冻结）':'')).join('、'):'暂无'}</span></div><TagSummary tags={a.tag_summary?.tags??[]} total={a.tag_summary?.total??0}/><p className="archive-row-excerpt">{a.search_match?<><small>观察命中 · </small><Highlight text={a.search_match.excerpt} query={pref.query}/></>:a.latest_observation??'还没有观察记录'}</p>{draftIds.includes(a.id)&&<span className="draft-badge">有草稿</span>}<div className="archive-row-footer"><span>{a.observation_count} 条观察</span><time>{date(a.updated_at)}</time></div></div></button>)}</div>
   {loading?<p className="archive-list-message" role="status">正在读取档案…</p>:error?null:!items.length?<div className="archive-list-message"><h2>{query||pref.scope!=='all'||pref.status||pref.member_id||pref.closed!=='all'?'没有符合条件的档案':'从第一个档案开始'}</h2><p>{query?'试试其他关键词，或清除筛选。':`把值得关注的${label}留在这里，慢慢积累观察。`}</p></div>:cursor&&<button className="button archive-load" onClick={()=>void load(cursor)}>加载更多档案</button>}
  </section>
  <section className="archive-detail-panel" aria-label="档案详情">
   {pref.selected?<ArchiveDetail focus={focus} actor={actor} onChanged={()=>setRevision(n=>n+1)} key={pref.selected} id={pref.selected} revision={revision} onLoaded={setSelected} onBack={()=>choose(null)} onEdit={()=>selected&&setDialog(selected)} onState={()=>selected&&setStateDialog(selected)} notice={notice}/>:<div className="archive-welcome"><p className="eyebrow">持续观察 · 共同沉淀</p><Avatar type={type} size="large"/><h2>留意那些<br/>值得了解的{label==='人物'?'人':'伙伴'}。</h2><p>从左侧打开一份档案，或创建新的关注对象。</p></div>}
  </section>
  {dialog&&<Modal title={dialog==='create'?`新建${label}档案`:'编辑档案资料'} busy={busy} onClose={()=>setDialog(null)}><ArchiveForm key={dialog==='create'?'create':dialog.id+dialog.version} type={type} initial={dialog==='create'?undefined:dialog} busy={busy} setBusy={setBusy} onSaved={saved} onReload={async()=>{if(dialog==='create')return;const r=await api<{archive:Archive}>('/archives/'+dialog.id);setDialog(r.archive);setRevision(n=>n+1);}}/></Modal>}
  {stateDialog&&<Modal title={stateDialog.closed?'重新开启档案':'状态与成员'} busy={busy} onClose={()=>setStateDialog(null)}><ArchiveStateForm key={stateDialog.id+stateDialog.version} archive={stateDialog} busy={busy} setBusy={setBusy} onSaved={saved} onReload={async()=>{const r=await api<{archive:Archive}>('/archives/'+stateDialog.id);setStateDialog(r.archive);setRevision(n=>n+1);}}/></Modal>}
 </main>;
}
function ArchiveDetail({actor,onChanged,id,revision,onLoaded,onBack,onEdit,onState,notice,focus}:{focus?:ObservationFocus;actor:Member;onChanged:()=>void;id:string;revision:number;onLoaded:(a:Archive)=>void;onBack:()=>void;onEdit:()=>void;onState:()=>void;notice:string}){
 const[archive,setArchive]=useState<Archive|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[copy,setCopy]=useState('');
 useEffect(()=>{let cancelled=false;setError('');api<{archive:Archive}>('/archives/'+id).then(r=>{if(!cancelled){setArchive(r.archive);onLoaded(r.archive);}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[id,revision,retry]);
 async function copyContact(value:string){try{await navigator.clipboard.writeText(value);setCopy('联系方式已复制');}catch{setCopy('复制未完成，请选择联系方式文字复制');}}
 return <><div className="archive-detail-top detail-top"><button className="button quiet archive-back" onClick={onBack}>← 返回列表</button><span>{archive?.type==='org'?'组织':'人物'}档案</span><span className="detail-number">{archive?.closed?'已关闭':'持续观察'}</span></div><PageError error={error} retry={()=>setRetry(n=>n+1)}/>{!archive&&!error?<p className="archive-list-message" role="status">正在打开档案…</p>:archive&&<div className="archive-detail-inner detail-inner">
  <header className="archive-profile entity-header"><div className="archive-identity entity-identity"><div className="entity-heading"><h1>{archive.name}</h1><button className={'state-badge '+(archive.closed?'closed':'')} onClick={onState} aria-label="调整状态与成员">{archive.status}<span aria-hidden="true">⌄</span></button></div>{archive.closed?<Avatar name={archive.name} type={archive.type} size="large" src={avatarUrl('archive',archive.id,archive.version)}/>:<AvatarEditor actorId={actor.id} subjectType="archive" id={archive.id} version={archive.version} name={archive.name} kind={archive.type} avatarId={archive.avatar_id} onSaved={onChanged}/>}</div>
   <div className="archive-responsibility assignment-row"><span className="assignment-label">{isWorkState(archive.type,archive.status)&&<span className="assignment-flag">◆ </span>}{memberLabel(archive.type,archive.status)}</span><div className="assigned-members">{archive.members.length?archive.members.map(m=><span key={m.id} className="member-chip"><Avatar name={m.name} size="tiny" src={avatarUrl('member',m.id,0)}/>{m.name}{m.frozen&&<small>已冻结</small>}</span>):<span className="optional-label">暂未关联</span>}</div><button className="button quiet" onClick={onState}>{archive.closed?'重新开启':archive.members.length?'调整':'关联'}</button></div>
   <div className="contacts-bar">{archive.contacts.map((c,i)=><button className="contact-pill" key={i} title={c.note||`复制${c.type}`} onClick={()=>void copyContact(c.value)}><small>{c.type}</small><span>{c.value}</span><span aria-hidden="true">⧉</span></button>)}{!archive.closed&&<button className="button quiet" onClick={onEdit}>编辑资料 ↗</button>}</div>
   {archive.links.length>0&&<ul className="archive-links">{archive.links.map((l,i)=><li key={i}><a href={l.url} target="_blank" rel="noopener noreferrer">{l.label||l.url} ↗</a></li>)}</ul>}
   {archive.closed&&<p className="archive-readonly">只读档案，重新开启后可继续维护。</p>}{copy&&<p className="form-notice" role="status">{copy}</p>}{notice&&<p className="form-notice" role="status">{notice}</p>}
  </header><TagsSection archive={archive} onChanged={onChanged}/><ObservationSection focus={focus} actor={actor} archive={archive} onChanged={onChanged}/>
 </div>}</>;
}

function ArchiveForm({type,initial,busy,setBusy,onSaved,onReload}:{type:Kind;initial?:Archive;busy:boolean;setBusy:(b:boolean)=>void;onSaved:(id:string,changed:boolean)=>Promise<void>;onReload:()=>Promise<void>}){
 const[name,setName]=useState(initial?.name??''),[contacts,setContacts]=useState(initial?.contacts??[]),[links,setLinks]=useState(initial?.links??[]),[error,setError]=useState(''),[requestId]=useState(()=>crypto.randomUUID()),[similar,setSimilar]=useState<Archive[]>([]),[status,setStatus]=useState('视奸观察'),[members,setMembers]=useState<BoundMember[]>([]);
 useEffect(()=>{if(initial||!name.trim()){setSimilar([]);return;}let cancelled=false;const timer=setTimeout(()=>{api<{archives:Archive[]}>('/archives?'+new URLSearchParams({type,query:name,limit:'3'})).then(r=>{if(!cancelled)setSimilar(r.archives);}).catch(()=>{});},350);return()=>{cancelled=true;clearTimeout(timer);};},[name,initial,type]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<{id:string;changed:boolean}>(initial?'/archives/update':'/archives/create',{...(initial?{id:initial.id,expected_version:initial.version}:{type}),name,contacts,links,...(!initial?{status,member_ids:members.map(m=>m.id)}:{}),request_id:requestId});await onSaved(r.id,r.changed);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="manage-form archive-form" onSubmit={save}>
  <label>{type==='person'?'昵称':'组织名称'}<input required maxLength={120} autoFocus value={name} onChange={e=>setName(e.target.value)}/></label>
  {similar.length>0&&<p className="similar-archives">已有相似档案：{similar.map(a=>a.name).join('、')}。同名不同对象可以继续创建。</p>}
  <fieldset><legend>联系方式 <small>可选</small></legend>{contacts.map((c,i)=><div className="archive-field-row" key={i}><div className="contact-main"><label>类型<select value={c.type} aria-label={`联系方式${i+1}类型`} onChange={e=>setContacts(old=>old.map((v,n)=>n===i?{...v,type:e.target.value}:v))}>{['QQ','微信','邮箱','电话','网站','其他',...(!['QQ','微信','邮箱','电话','网站','其他'].includes(c.type)?[c.type]:[])].map(v=><option key={v}>{v}</option>)}</select></label><label>联系方式<input required value={c.value} maxLength={500} aria-label={`联系方式${i+1}`} onChange={e=>setContacts(old=>old.map((v,n)=>n===i?{...v,value:e.target.value}:v))}/></label><button type="button" className="icon-close" aria-label={`移除联系方式${i+1}`} onClick={()=>setContacts(old=>old.filter((_,n)=>n!==i))}>×</button></div><label>备注<input value={c.note} maxLength={500} aria-label={`联系方式${i+1}备注`} onChange={e=>setContacts(old=>old.map((v,n)=>n===i?{...v,note:e.target.value}:v))}/></label></div>)}<button type="button" className="button quiet" disabled={contacts.length>=20} onClick={()=>setContacts(old=>[...old,{type:'QQ',value:'',note:''}])}>＋ 添加联系方式</button></fieldset>
  <fieldset><legend>资料链接 <small>可选</small></legend>{links.map((l,i)=><div className="archive-field-row" key={i}><label>链接名称<input value={l.label} maxLength={100} aria-label={`资料链接${i+1}名称`} onChange={e=>setLinks(old=>old.map((v,n)=>n===i?{...v,label:e.target.value}:v))}/></label><div className="link-main"><label>网址<input type="url" required maxLength={2000} value={l.url} aria-label={`资料链接${i+1}网址`} onChange={e=>setLinks(old=>old.map((v,n)=>n===i?{...v,url:e.target.value}:v))}/></label><button type="button" className="icon-close" aria-label={`移除资料链接${i+1}`} onClick={()=>setLinks(old=>old.filter((_,n)=>n!==i))}>×</button></div></div>)}<button type="button" className="button quiet" disabled={links.length>=20} onClick={()=>setLinks(old=>[...old,{label:'',url:''}])}>＋ 添加资料链接</button></fieldset>
  {!initial&&<StateFields type={type} status={status} onStatus={s=>{setStatus(s);setMembers([]);}} members={members} onMembers={setMembers}/>}
  <PageError error={error} retry={initial?()=>void onReload().catch(e=>setError(e.message)):undefined} retryLabel="重新读取并替换表单"/><div className="dialog-actions"><button className="button primary" disabled={busy||(!initial&&isWorkState(type,status)&&members.length===0)}>{busy?'正在保存…':initial?'保存资料':'创建档案'}</button></div>
 </form>;
}
