import React,{useEffect,useState,type FormEvent} from 'react';
import {api,type Member} from './api';
import {Avatar} from './Avatar';
import {Modal,ModalActions} from './Modal';
import {pasteImages,ImagePicker,type AttachmentInfo} from './Images';
import {PageError} from './ConnectionPages';
import {pushableTaskKinds,type PushableTaskKind} from '../shared/task-preferences';
export function avatarUrl(type:'archive'|'member',id:string,version:number){return `/avatars/${type==='archive'?'archives':'members'}/${id}?v=${version}`;}
export function AvatarEditor({actorId,subjectType,id,version,name,kind='person',avatarId,onSaved}:{actorId:string;subjectType:'archive'|'member';id:string;version:number;name:string;kind?:'person'|'org';avatarId:string|null;onSaved:()=>Promise<unknown>|void}){
 const[open,setOpen]=useState(false),[images,setImages]=useState<AttachmentInfo[]>([]),[pending,setPending]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[request,setRequest]=useState<{id:string;attachment:string|null}|null>(null);
 async function save(attachment:string|null){setBusy(true);setError('');const cmd=request?.attachment===attachment?request:{id:crypto.randomUUID(),attachment};setRequest(cmd);try{await api('/avatars/set',{subject_type:subjectType,id,expected_version:version,attachment_id:attachment,request_id:cmd.id});setImages([]);setOpen(false);setRequest(null);await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button className="avatar-edit-button" type="button" onClick={()=>setOpen(true)} aria-label={`修改${name}的头像`}><Avatar name={name} type={kind} size="large" src={avatarUrl(subjectType,id,version)}/><small>修改头像</small></button>{open&&<Modal title="修改头像" busy={busy} onClose={()=>setOpen(false)}><div className="avatar-editor" onPaste={e=>{if(!busy)setError(pasteImages(e,actorId+':avatar:'+subjectType+':'+id,subjectType==='archive'?{purpose:'archive_avatar',archive_id:id}:{purpose:'member_avatar',member_id:id},images.length,1));}}><p>{kind==='org'?'组织头像未上传时显示默认图形。':'上传头像优先显示；移除后恢复 QQ 头像，无可用 QQ 头像时显示默认图形。'}</p><ImagePicker queueKey={actorId+':avatar:'+subjectType+':'+id} target={subjectType==='archive'?{purpose:'archive_avatar',archive_id:id}:{purpose:'member_avatar',member_id:id}} value={images} onChange={setImages} onPending={setPending} disabled={busy} max={1}/><PageError error={error} retry={()=>void Promise.resolve(onSaved()).catch(e=>setError(e.message))} retryLabel="刷新资料版本"/><ModalActions>{avatarId&&<button className="button quiet" type="button" disabled={busy||pending} onClick={()=>void save(null)}>移除上传头像</button>}<button className="button primary" type="button" disabled={busy||pending||!images.length} onClick={()=>void save(images[0].id)}>{busy?'正在保存…':'使用这张头像'}</button></ModalActions></div></Modal>}</>;
}
export function ProfilePage({actor,refreshActor}:{actor:Member;refreshActor:()=>Promise<Member|null>}){
 const[name,setName]=useState(actor.name),[qq,setQQ]=useState(actor.qq??''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[request,setRequest]=useState<{key:string;id:string}|null>(null);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');const key=JSON.stringify([actor.version,name,qq]),cmd=request?.key===key?request:{key,id:crypto.randomUUID()};setRequest(cmd);try{await api('/profile',{id:actor.id,expected_version:actor.version,name,qq:qq||null,request_id:cmd.id});await refreshActor();setRequest(null);setNotice('个人资料已保存');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const kinds:Record<PushableTaskKind,string>={audit:'人事审核',onboarding:'入社对接',monthly:'月度沟通',cooperation:'组织合作'};
 const[preference,setPreference]=useState<{all:boolean;kinds:PushableTaskKind[];version:number}|null>(null),[preferenceError,setPreferenceError]=useState(''),[preferenceNotice,setPreferenceNotice]=useState(''),[preferenceBusy,setPreferenceBusy]=useState(false),[preferenceRequest,setPreferenceRequest]=useState<{key:string;id:string}|null>(null);
 useEffect(()=>{let active=true;api<{preference:{all:boolean;kinds:PushableTaskKind[];version:number}}>('/profile/work-preference').then(r=>{if(active)setPreference(r.preference)}).catch(e=>{if(active)setPreferenceError((e as Error).message)});return()=>{active=false;};},[actor.id]);
 async function savePreference(e:FormEvent){e.preventDefault();if(!preference)return;setPreferenceBusy(true);setPreferenceError('');const key=JSON.stringify([preference.version,preference.all,preference.kinds]),cmd=preferenceRequest?.key===key?preferenceRequest:{key,id:crypto.randomUUID()};setPreferenceRequest(cmd);try{const r=await api<{all:boolean;kinds:PushableTaskKind[];version:number;changed:boolean}>('/profile/work-preference',{all:preference.all,kinds:preference.kinds,expected_version:preference.version,request_id:cmd.id});setPreference({...r});setPreferenceRequest(null);setPreferenceNotice(r.changed?'工作倾向已更新':'没有变化');}catch(e){setPreferenceError((e as Error).message);}finally{setPreferenceBusy(false);}}
 return <main className="account-content"><div className="section-title"><p className="eyebrow">猎头账号</p><h1>我的资料</h1></div><AvatarEditor actorId={actor.id} subjectType="member" id={actor.id} version={actor.version} name={actor.name} avatarId={actor.avatar_id} onSaved={refreshActor}/><form className="manage-form" onSubmit={save}><p>登录账号：{actor.username}</p><label>显示名称<input value={name} onChange={e=>setName(e.target.value)} required maxLength={80} disabled={busy}/></label><label>QQ（可选）<input value={qq} onChange={e=>setQQ(e.target.value)} inputMode="numeric" pattern="[0-9]{5,20}" maxLength={20} disabled={busy}/><small>用于显示 QQ 头像。</small></label><PageError error={error} retry={()=>void refreshActor().catch(e=>setError(e.message))} retryLabel="刷新资料版本"/>{notice&&<p className="form-notice" role="status">{notice}</p>}<button className="button primary" disabled={busy}>{busy?'正在保存…':'保存资料'}</button></form><section className="manage-form work-preference-form"><div className="section-title"><p className="eyebrow">任务提醒</p><h2>我的工作倾向</h2><p>只用于匹配推荐提醒，不代表能力认证，也不影响你从全组看板主动领取。</p></div>{preferenceError&&<PageError error={preferenceError} retry={()=>api<{preference:{all:boolean;kinds:PushableTaskKind[];version:number}}>('/profile/work-preference').then(r=>setPreference(r.preference)).catch(e=>setPreferenceError(e.message))}/>} {preferenceNotice&&<p className="form-notice" role="status">{preferenceNotice}</p>}{preference&&<form onSubmit={savePreference}><label className="preference-all"><input type="checkbox" checked={preference.all} disabled={preferenceBusy} onChange={e=>setPreference({...preference,all:e.target.checked})}/><span><strong>全能</strong><small>愿意收到所有有明确类型的工作提醒</small></span></label><fieldset disabled={preferenceBusy||preference.all}><legend>愿意接手的工作</legend>{pushableTaskKinds.map(kind=><label key={kind} className="preference-choice"><input type="checkbox" checked={preference.kinds.includes(kind)} onChange={e=>setPreference({...preference,kinds:e.target.checked?[...preference.kinds,kind]:preference.kinds.filter(k=>k!==kind)})}/><span>{kinds[kind]}</span></label>)}</fieldset><button className="button primary" disabled={preferenceBusy}>{preferenceBusy?'正在保存…':'保存工作倾向'}</button></form>}</section></main>;
}
