import React,{useEffect,useRef,useState,lazy,Suspense} from 'react';
import {api,type Member} from './api';
import type {Archive} from '../server/archives';
import type {MaterialInfo,MaterialCapacity} from '../server/materials';
import {MaterialList,MaterialEditForm,MaterialQuotaForm,fileSize} from '../ui/Materials';
import {Modal} from './Modal';

const PdfPreview=lazy(()=>import('../ui/PdfPreview'));
type Prepared={upload_id:string;url:string;headers:Record<string,string>;expires_at:string};
type Upload={id:string;file:File;phase:'waiting'|'hashing'|'uploading'|'error'|'done';progress:number;error?:string;prepared?:Prepared};
type Dialog={action:'edit'|'delete'|'restore'|'purge';file:MaterialInfo;requestId:string}|{action:'quota';capacity:MaterialCapacity;requestId:string}|{action:'preview';file:MaterialInfo};
export function MaterialsSection({actor,archive,onChanged,active}:{actor:Member;archive:Archive;onChanged:()=>void;active:boolean}){
 const[items,setItems]=useState<MaterialInfo[]>([]),[capacity,setCapacity]=useState<MaterialCapacity|null>(null),[deleted,setDeleted]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[cursor,setCursor]=useState<string|null>(null),[uploads,setUploads]=useState<Upload[]>([]),[dialog,setDialog]=useState<Dialog|null>(null),[busy,setBusy]=useState(false),[dialogError,setDialogError]=useState('');
 const[focusId]=useState(()=>{const p=new URLSearchParams(location.search);return p.get('archive')===archive.id?p.get('material')??undefined:undefined;});
 const scopeRef=useRef(deleted),focusHandled=useRef(false);scopeRef.current=deleted;
 const serial=useRef(0),mounted=useRef(true),processing=useRef(false),queue=useRef<Upload[]>([]),xhr=useRef<XMLHttpRequest|null>(null),callback=useRef(onChanged);callback.current=onChanged;
 function sync(){if(mounted.current)setUploads([...queue.current]);}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;serial.current++;xhr.current?.abort();};},[]);
 useEffect(()=>{if(!uploads.some(u=>['waiting','hashing','uploading'].includes(u.phase)))return;const leave=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[uploads]);
 async function load(before?:string){const sequence=++serial.current,scope=scopeRef.current;setLoading(true);setError('');try{const r=await api<{materials:MaterialInfo[];capacity:MaterialCapacity;next_cursor:string|null}>('/materials?'+new URLSearchParams({archive_id:archive.id,deleted:String(scope),...(before?{before}:{})}));if(!mounted.current||sequence!==serial.current)return;setItems(old=>before?[...new Map([...old,...r.materials].map(f=>[f.id,f])).values()]:r.materials);setCapacity(r.capacity);setCursor(r.next_cursor);if(!before&&focusId&&!focusHandled.current){focusHandled.current=true;if(!r.materials.some(f=>f.id===focusId))try{const f=(await api<{material:MaterialInfo}>('/materials/'+focusId)).material;if(f.archive_id!==archive.id)throw new Error('引用的材料不属于当前档案');if(sequence===serial.current){if(f.deleted&&!scope){changeScope(true);return;}if(f.deleted===scope)setItems(old=>[f,...old]);}}catch(e){if(sequence===serial.current)setError((e as Error).message);}}}catch(e){if(sequence===serial.current)setError((e as Error).message);}finally{if(mounted.current&&sequence===serial.current)setLoading(false);}}
 useEffect(()=>{if(active)void load();return()=>{serial.current++;};},[archive.id,archive.version,deleted,active]);
 async function refresh(){await load();callback.current();}
 function changeScope(next:boolean){if(next===scopeRef.current)return;scopeRef.current=next;serial.current++;setItems([]);setCursor(null);setLoading(true);setError('');setDeleted(next);}
 function open(action:'edit'|'delete'|'restore'|'purge',file:MaterialInfo){setDialogError('');setDialog({action,file,requestId:crypto.randomUUID()});}
 async function perform(body:Record<string,unknown>){if(!dialog||dialog.action==='preview')return;setBusy(true);setDialogError('');try{const result=await api<{state?:string}>('/materials/'+(dialog.action==='edit'?'update':dialog.action),{...body,request_id:dialog.requestId});setNotice(result.state==='purging'?'清除已提交，文件正在清理。':dialog.action==='quota'?'材料容量已保存':dialog.action==='edit'?'材料已保存':dialog.action==='delete'?'材料已移入回收站':dialog.action==='restore'?'材料已恢复':'材料已彻底删除');setDialog(null);await refresh();}catch(e){setDialogError((e as Error).message);}finally{setBusy(false);}}
 async function reloadDialog(){if(!dialog||dialog.action==='preview')return;setDialogError('');try{if(dialog.action==='quota')setDialog({...dialog,capacity:await api<MaterialCapacity>('/material-capacity/'+archive.id),requestId:crypto.randomUUID()});else setDialog({...dialog,file:(await api<{material:MaterialInfo}>('/materials/'+dialog.file.id)).material,requestId:crypto.randomUUID()});}catch(e){setDialogError((e as Error).message);}}
 const send=(u:Upload)=>new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();xhr.current=request;request.open('PUT',u.prepared!.url);for(const[k,v]of Object.entries(u.prepared!.headers))request.setRequestHeader(k,v);request.upload.onprogress=e=>{if(e.lengthComputable){u.progress=Math.round(e.loaded/e.total*100);sync();}};request.onload=()=>{if(request.status>=200&&request.status<300)resolve();else{let message='上传失败，请查询后重试';try{message=JSON.parse(request.responseText).error.message;}catch{}reject(new Error(message));}};request.onerror=()=>reject(new Error('网络中断，上传结果待确认'));request.onabort=()=>reject(new Error('上传已中止'));request.send(u.file);});
 async function process(){if(processing.current)return;processing.current=true;try{while(mounted.current){const u=queue.current.find(u=>u.phase==='waiting');if(!u)break;try{
    if(u.prepared){const status=await api<{state:string}>('/material-uploads/'+u.prepared.upload_id);if(status.state==='ready'){u.phase='done';queue.current=queue.current.filter(item=>item!==u);sync();await refresh();continue;}if(status.state==='uploading')throw new Error('服务端仍在接收文件，请稍后重试查询');if(status.state!=='pending'||u.prepared.expires_at<=new Date().toISOString())u.prepared=undefined;}
    if(!u.prepared){u.phase='hashing';sync();const bytes=await u.file.arrayBuffer(),sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');if(!mounted.current)break;u.prepared=await api<Prepared>('/materials/prepare',{archive_id:archive.id,name:u.file.name,mime_type:u.file.type||'application/octet-stream',byte_size:u.file.size,sha256});}
    if(!mounted.current){await api('/materials/cancel',{id:u.prepared.upload_id,request_id:crypto.randomUUID()}).catch(()=>{});break;}u.phase='uploading';sync();await send(u);const status=await api<{state:string}>('/material-uploads/'+u.prepared.upload_id);if(status.state!=='ready')throw new Error('上传结果尚未确认，请重试查询');u.phase='done';queue.current=queue.current.filter(item=>item!==u);sync();if(mounted.current)await refresh();
   }catch(e){u.phase='error';u.error=(e as Error).message;sync();if(mounted.current)void load();}finally{xhr.current=null;}}
  }finally{processing.current=false;}}
 function addFiles(files:File[]){if(deleted)changeScope(false);setNotice('');setError('');if(files.length+queue.current.filter(u=>u.phase!=='done').length>50){setError('一次最多处理 50 个文件，请分批上传');return;}for(const file of files){const valid=file.size>0&&file.size<=100_000_000;queue.current.push({id:crypto.randomUUID(),file,phase:valid?'waiting':'error',progress:0,...(!valid?{error:file.size?'单文件不能超过 100MB':'不能上传空文件'}:{})});}sync();void process();}
 async function removeUpload(u:Upload){try{if(u.prepared)await api('/materials/cancel',{id:u.prepared.upload_id,request_id:crypto.randomUUID()});queue.current=queue.current.filter(x=>x!==u);sync();void load();}catch(e){u.error=(e as Error).message;sync();}}
 async function copy(file:MaterialInfo){try{await navigator.clipboard.writeText(file.reference_url);setNotice('材料引用已复制，可粘贴到观察记录');}catch{setError('未能复制引用，请重试');}}
 return <><MaterialList items={items} capacity={capacity} deleted={deleted} onDeleted={changeScope} onFiles={addFiles} onEdit={f=>open('edit',f)} onDelete={f=>open('delete',f)} onRestore={f=>open('restore',f)} onPurge={f=>open('purge',f)} onPreview={file=>setDialog({action:'preview',file})} onCopy={copy} onQuota={actor.role==='admin'&&capacity?()=>{setDialogError('');setDialog({action:'quota',capacity,requestId:crypto.randomUUID()});}:undefined} locked={archive.closed||archive.deleted} loading={loading} error={error} onRetry={()=>void load()} more={!!cursor} onMore={()=>void load(cursor!)} focusId={focusId}>
  {notice&&<p className="form-notice" role="status">{notice}</p>}{uploads.filter(u=>u.phase!=='done').map(u=><div className="material-upload" key={u.id}><strong>{u.file.name}</strong> <small>{fileSize(u.file.size)} · {u.phase==='waiting'?'等待上传':u.phase==='hashing'?'正在校验文件':u.phase==='uploading'?`正在上传 ${u.progress}%`:'上传未完成'}</small>{u.phase==='uploading'&&<progress value={u.progress} max={100} aria-label={'上传 '+u.file.name}/>} {u.error&&<p className="form-error" role="alert">{u.error}</p>}{u.phase==='error'&&<div className="material-upload-actions"><button className="text-button" onClick={()=>{u.phase='waiting';u.error='';sync();void process();}}>重试上传</button><button className="text-button" onClick={()=>void removeUpload(u)}>取消上传</button></div>}</div>)}
 </MaterialList>
 {dialog&&<Modal wide={dialog.action==='preview'} title={dialog.action==='edit'?'名称与说明':dialog.action==='quota'?'调整材料容量':dialog.action==='preview'?dialog.file.name:dialog.action==='delete'?'删除材料':dialog.action==='restore'?'恢复材料':'彻底删除材料'} busy={busy} onClose={()=>setDialog(null)}>
  {dialog.action==='edit'?<MaterialEditForm key={dialog.file.id+':'+dialog.file.version} file={dialog.file} busy={busy} error={dialogError} onSubmit={(name,description)=>void perform({id:dialog.file.id,expected_version:dialog.file.version,name,description})} onCancel={()=>setDialog(null)} onReload={()=>void reloadDialog()}/>:dialog.action==='quota'?<MaterialQuotaForm key={dialog.capacity.version} capacity={dialog.capacity} busy={busy} error={dialogError} onSubmit={limit_bytes=>void perform({archive_id:archive.id,expected_version:dialog.capacity.version,limit_bytes})} onCancel={()=>setDialog(null)} onReload={()=>void reloadDialog()}/>:dialog.action==='preview'?<MaterialPreview file={dialog.file}/>:<div className="material-form"><strong>{dialog.file.name}</strong><p>{dialog.action==='delete'?'删除后可在回收站恢复，文件仍占容量。':dialog.action==='restore'?'恢复后将重新出现在全部材料中。':'将永久清除这份在线材料，无法从回收站恢复。'}</p>{dialogError&&<p className="form-error" role="alert">{dialogError} <button className="text-button" onClick={()=>void reloadDialog()}>重新读取材料</button></p>}<div className="modal-actions"><button className="button quiet" disabled={busy} onClick={()=>setDialog(null)}>取消</button><button className={'button '+(dialog.action==='restore'?'primary':'danger')} disabled={busy} onClick={()=>void perform({id:dialog.file.id,expected_version:dialog.file.version})}>{busy?'正在处理…':dialog.action==='delete'?'确认删除':dialog.action==='restore'?'确认恢复':'确认彻底删除'}</button></div></div>}
 </Modal>}</>;
}
function MaterialPreview({file}:{file:MaterialInfo}){const[url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{const controller=new AbortController();let objectUrl='';fetch(file.preview_url!,{credentials:'same-origin',cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok){let message='材料暂不可预览';try{message=((await r.json()) as {error:{message:string}}).error.message;}catch{}throw new Error(message);}return r.blob();}).then(blob=>{if(!controller.signal.aborted){objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[file.id]);return error?<p className="form-error" role="alert">{error}</p>:!url?<p role="status">正在载入预览…</p>:<>{file.mime_type==='application/pdf'?<Suspense fallback={<p role="status">正在载入 PDF 预览…</p>}><PdfPreview url={url}/></Suspense>:<img src={url} alt={file.name} className="material-preview" onError={()=>setError('无法预览此图片，请下载原文件查看')}/>}<p><a href={file.download_url}>下载原文件</a></p></>;}
