import {avatarUrl} from './AvatarEditor';
import React,{useEffect,useState,type FormEvent} from 'react';
import {api,type Member} from './api';
import {PageError} from './ConnectionPages';
import {Avatar} from './Avatar';
import {Modal} from './Modal';

type ManagedMember=Member&{frozen:boolean;created_at:string};
type Dialog={type:'edit'|'reset'|'history';member:ManagedMember}|{type:'create'};
const makePassword=()=>Array.from(crypto.getRandomValues(new Uint8Array(24)),n=>n.toString(16).padStart(2,'0')).join('');
function TemporaryPassword({password,onSaved}:{password:string;onSaved:(saved:boolean)=>void}){
  const[copied,setCopied]=useState(false),[message,setMessage]=useState('');
  return <section className="temporary-password"><label>新临时密码<input readOnly value={password} autoComplete="off" onFocus={e=>e.currentTarget.select()}/></label><p>先保存并私下交付给成员，首次登录需要更换。</p><button type="button" className="button" onClick={async()=>{try{await navigator.clipboard.writeText(password);setCopied(true);onSaved(true);setMessage('临时密码已复制');}catch{setMessage('请选择上方密码复制，再勾选已保存');}}}>复制临时密码</button><label className="check-label"><input type="checkbox" checked={copied} onChange={e=>{setCopied(e.target.checked);onSaved(e.target.checked);}}/>我已安全保存临时密码</label>{message&&<p role="status">{message}</p>}</section>;
}
export function MembersPage({actor,refreshActor}:{actor:Member;refreshActor:(message?:string)=>Promise<Member|null>}){
  const[items,setItems]=useState<ManagedMember[]>([]),[next,setNext]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState<Dialog|null>(null),[busy,setBusy]=useState(false);
  async function load(cursor?:string){setLoading(true);setError('');try{const r=await api<{members:ManagedMember[];next_cursor:string|null}>('/admin/members'+(cursor?'?before='+encodeURIComponent(cursor):''));setItems(old=>cursor?[...old,...r.members]:r.members);setNext(r.next_cursor);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function saved(message:string){setNotice(message);setDialog(null);const refreshed=await refreshActor(message);if(refreshed?.role==='admin')await load();}
  async function reloadMember(member:ManagedMember){setError('');try{const r=await api<{member:ManagedMember}>('/admin/members/'+member.id);setItems(old=>old.map(x=>x.id===member.id?r.member:x));setDialog({type:'edit',member:r.member});}catch(e){setError((e as Error).message);}}
  return <main className="account-content"><div className="section-title section-title-actions"><div><p className="eyebrow">一起观察的人</p><h1>猎头管理</h1><p>管理成员账号与访问权限。</p></div><button className="button primary" onClick={()=>{setError('');setDialog({type:'create'});}}>创建猎头账号</button></div><PageError error={error} retry={()=>void load()}/>{notice&&<p className="form-notice" role="status">{notice}</p>}
    <table className="member-table"><thead><tr><th>猎头账号</th><th>角色</th><th>状态</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{items.map(m=><tr key={m.id}><td><div className="managed-identity"><Avatar name={m.name} size="tiny" src={avatarUrl('member',m.id,m.version)}/><div><strong>{m.name}</strong>{m.id===actor.id&&<span className="self-label">你</span>}<small>{m.username}</small></div></div></td><td><span className="cell-label">角色</span>{m.role==='admin'?'管理员':'普通成员'}</td><td><span className="cell-label">状态</span><span className={'account-state '+(m.frozen?'frozen':'')}>{m.frozen?'已冻结':m.must_change_password?'待首次改密':'正常'}</span></td><td><button className="button quiet" aria-label={`管理 ${m.name}`} onClick={()=>{setError('');setDialog({type:'edit',member:m});}}>管理 →</button></td></tr>)}</tbody></table>{loading?<p role="status">正在读取账号…</p>:items.length===0?<p className="empty-state">没有可显示的猎头账号。</p>:next&&<button className="button" onClick={()=>void load(next)}>加载更多</button>}
    {dialog&&<Modal title={dialog.type==='create'?'创建猎头账号':dialog.type==='reset'?'重置临时密码':dialog.type==='history'?'账号管理历史':'管理猎头账号'} onClose={()=>setDialog(null)} busy={busy}>
      {dialog.type==='create'?<CreateForm key="create" busy={busy} setBusy={setBusy} onSaved={saved}/>:dialog.type==='reset'?<ResetForm key={dialog.member.id+dialog.member.version} member={dialog.member} busy={busy} setBusy={setBusy} onSaved={saved} onReload={()=>void reloadMember(dialog.member)}/>:dialog.type==='history'?<MemberHistory member={dialog.member}/>:<EditForm key={dialog.member.id+dialog.member.version} member={dialog.member} busy={busy} setBusy={setBusy} onSaved={saved} onReload={()=>void reloadMember(dialog.member)} onReset={()=>setDialog({type:'reset',member:dialog.member})} onHistory={()=>setDialog({type:'history',member:dialog.member})}/>}
    </Modal>}
  </main>;
}
type FormProps={busy:boolean;setBusy:(value:boolean)=>void;onSaved:(message:string)=>Promise<void>};
function CreateForm({busy,setBusy,onSaved}:FormProps){
  const[password]=useState(makePassword),[saved,setSaved]=useState(false),[requestId]=useState(()=>crypto.randomUUID()),[error,setError]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{await api('/admin/members/create',{username:data.get('username'),name:data.get('name'),role:data.get('role'),qq:data.get('qq')||null,temporary_password:password,request_id:requestId});await onSaved('账号已创建，请私下交付保存的临时密码');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <form className="manage-form" onSubmit={submit}><label>登录账号<input name="username" autoFocus required minLength={3} maxLength={40} pattern="[a-zA-Z0-9_.-]+" autoComplete="off"/><small>3–40 位字母、数字、点、下划线或连字符，创建后保持不变。</small></label><label>显示名称<input name="name" required maxLength={80}/></label><div className="form-columns"><label>角色<select name="role" defaultValue="member"><option value="member">普通成员</option><option value="admin">管理员</option></select></label><label>QQ（可选）<input name="qq" inputMode="numeric" pattern="[0-9]{5,20}" maxLength={20}/></label></div><TemporaryPassword password={password} onSaved={setSaved}/><PageError error={error}/><div className="dialog-actions"><button className="button primary" disabled={busy||!saved}>{busy?'正在创建…':'创建账号'}</button></div></form>;
}
function ResetForm({member,busy,setBusy,onSaved,onReload}:FormProps&{member:ManagedMember;onReload:()=>void}){
  const[password]=useState(makePassword),[saved,setSaved]=useState(false),[requestId]=useState(()=>crypto.randomUUID()),[error,setError]=useState('');
  async function reset(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/admin/members/reset-password',{id:member.id,expected_version:member.version,temporary_password:password,request_id:requestId});await onSaved('密码已重置，旧登录和连接已失效');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <form className="manage-form" onSubmit={reset}><p>重置 <strong>{member.name}</strong>（{member.username}）的密码。所有旧登录和连接会立即失效。</p><TemporaryPassword password={password} onSaved={setSaved}/><PageError error={error} retry={onReload}/><div className="dialog-actions"><button className="button primary" disabled={busy||!saved}>{busy?'正在重置…':'重置密码'}</button></div></form>;
}
function EditForm({member,busy,setBusy,onSaved,onReload,onReset,onHistory}:FormProps&{member:ManagedMember;onReload:()=>void;onReset:()=>void;onHistory:()=>void}){
  const[error,setError]=useState(''),[profileRequest]=useState(()=>crypto.randomUUID()),[roleRequest]=useState(()=>crypto.randomUUID()),[frozenRequest]=useState(()=>crypto.randomUUID());
  async function mutate(path:string,input:unknown,message:string){setBusy(true);setError('');try{await api(path,input);await onSaved(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);void mutate('/admin/members/profile',{id:member.id,expected_version:member.version,name:data.get('name'),qq:data.get('qq')||null,request_id:profileRequest},'账号资料已保存');}
  return <div className="manage-form"><p className="secondary-copy">登录账号：{member.username}</p><form onSubmit={save}><label>显示名称<input name="name" defaultValue={member.name} required maxLength={80}/></label><label>QQ（可选）<input name="qq" defaultValue={member.qq??''} inputMode="numeric" pattern="[0-9]{5,20}" maxLength={20}/></label><button className="button primary" disabled={busy}>保存资料</button></form><PageError error={error} retry={onReload}/><section className="member-access"><h3>访问权限</h3><p>当前为{member.role==='admin'?'管理员':'普通成员'}，账号{member.frozen?'已冻结':'正常'}。至少保留一名未冻结的管理员。</p><div className="inline-actions"><button className="button" disabled={busy} onClick={()=>void mutate('/admin/members/role',{id:member.id,expected_version:member.version,role:member.role==='admin'?'member':'admin',request_id:roleRequest},'成员角色已更新')}>{member.role==='admin'?'降为普通成员':'授予管理员'}</button><button className="button danger-text" disabled={busy} onClick={()=>void mutate('/admin/members/frozen',{id:member.id,expected_version:member.version,frozen:!member.frozen,request_id:frozenRequest},member.frozen?'已解冻，请重新登录并创建连接':'账号已冻结，旧登录和连接已失效')}>{member.frozen?'解冻账号':'冻结账号'}</button></div></section><section className="member-access"><h3>密码与历史</h3><div className="inline-actions"><button className="button" disabled={busy} onClick={onReset}>重置密码</button><button className="button quiet" disabled={busy} onClick={onHistory}>查看管理历史</button></div></section></div>;
}
function MemberHistory({member}:{member:ManagedMember}){
  const[data,setData]=useState<{events:{id:string;kind:string;actor_name:string|null;actor_id:string;source:string;created_at:string;before_json:string|null;after_json:string|null}[];complete:boolean}|null>(null),[error,setError]=useState('');
  useEffect(()=>{api<NonNullable<typeof data>>('/admin/members/'+member.id+'/history').then(setData).catch(e=>setError(e.message));},[member.id]);
  const kinds:Record<string,string>={'member.avatar_changed':'修改头像','member.created':'创建账号','member.password_reset':'重置密码','member.role_changed':'调整角色','member.frozen':'冻结账号','member.unfrozen':'解冻账号','member.profile_changed':'修改资料'};
  const labels:Record<string,string>={username:'登录账号',name:'显示名称',qq:'QQ',role:'角色',frozen:'账号状态',must_change_password:'首次改密',existing_credentials_invalidated:'旧登录与连接'};
  function value(key:string,v:unknown){if(v===undefined||v===null)return '未设置';if(key==='role')return v==='admin'?'管理员':'普通成员';if(key==='frozen')return v?'已冻结':'可用';if(key==='must_change_password')return v?'需要':'已完成';if(key==='existing_credentials_invalidated')return v?'已失效':'有效';return String(v);}
  return <section className="member-history"><p>{member.name} · {member.username}</p><PageError error={error}/>{!data&&!error?<p role="status">正在读取历史…</p>:data?.events.length===0?<p>还没有管理事件。</p>:data?.events.map(event=>{const before=event.before_json?JSON.parse(event.before_json):{},after=event.after_json?JSON.parse(event.after_json):{};return <article key={event.id}><strong>{kinds[event.kind]??event.kind}</strong><p>{event.actor_name??'历史成员'} · {event.source==='mcp'?'MCP':'网页'} · {new Date(event.created_at).toLocaleString('zh-CN')}</p><ul>{[...new Set([...Object.keys(before),...Object.keys(after)])].filter(k=>before[k]!==after[k]).map(k=><li key={k}>{labels[k]??k}：{value(k,before[k])} → {value(k,after[k])}</li>)}</ul></article>;})}{data&&!data.complete&&<p>当前显示最近 100 项管理事件。</p>}</section>;
}
