import React,{useEffect,useRef,useState,type FormEvent} from 'react';
import {TabList} from '../ui/Workspace';
import {api} from './api';
import {Modal,ModalActions} from './Modal';
import {PageError} from './ConnectionPages';
import {TagChip,TagEvidence,TagChooser} from './TagsSection';
import type {TagBinding} from '../server/tag-state';

type Kind='person'|'org';
type Definition={id:string;type:Kind;name:string;description:string;category_id?:string;category_name?:string;color:string;version:number;enabled:number;merged_into?:string|null};
type Counts={archives:number;bindings:number;open:number;closed:number};
type Detail={definition:Definition;counts:Counts;can_administer:boolean;history:{version:number;definition:Definition&{reason?:string};actor_name:string;created_at:string}[];next_cursor:number|null};
type Impact={preview_id:string;diff:{field:string;before:unknown;after:unknown}[];counts:Counts;changed:boolean};
const fields:Record<string,string>={name:'名称',description:'释义',category_id:'类别',color:'颜色'};
const fullName=(d:Definition)=>d.category_name?`${d.category_name}：${d.name}`:d.name;
export function TagFilter({type,ids,onChange}:{type:Kind;ids:string[];onChange:(ids:string[])=>void}){
 const[open,setOpen]=useState(false),[labels,setLabels]=useState<Record<string,Definition>>({}),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;void Promise.all(ids.filter(id=>!labels[id]).map(async id=>{const r=await api<Detail>('/tag-definitions/tag/'+id);return r.definition;})).then(rows=>{if(!cancelled)setLabels(old=>({...old,...Object.fromEntries(rows.map(r=>[r.id,r]))}));}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[ids.join(',')]);
 return <div className="tag-filter"><button type="button" className="button" onClick={()=>setOpen(true)}>筛选标签{ids.length?` · ${ids.length}`:''}</button>{open&&<Modal title="筛选标签" busy={false} onClose={()=>setOpen(false)}><p className="secondary-copy">同类别满足任一项，不同类别需同时满足。</p><div className="selected-tag-filters">{ids.map(id=><button className="button quiet" key={id} onClick={()=>onChange(ids.filter(x=>x!==id))}>{labels[id]?fullName(labels[id]):'已选标签'} ×</button>)}</div><PageError error={error}/><TagChooser type={type} allowCreate={false} includeDisabled selectLabel="选择" boundIds={ids} onSelect={async id=>{if(ids.length>=30)throw new Error('最多选择 30 个筛选标签');onChange([...ids,id]);}}/><ModalActions><button className="button primary" onClick={()=>setOpen(false)}>查看结果</button></ModalActions></Modal>}</div>;
}
export function TagDefinitionDialog({entityType,id,onClose,onChanged}:{entityType:'tag'|'category';id:string;onClose:()=>void;onChanged:()=>void}){
 const[detail,setDetail]=useState<Detail|null>(null),[tab,setTab]=useState('definition'),[error,setError]=useState(''),[revision,setRevision]=useState(0),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[operation,setOperation]=useState<'meaning_change'|'merge'|'availability'|null>(null),[related,setRelated]=useState<string|null>(null);
 async function load(){try{setError('');setDetail(await api<Detail>(`/tag-definitions/${entityType}/${id}`));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[id,entityType,revision]);
 async function history(){if(!detail?.next_cursor)return;try{const r=await api<Detail>(`/tag-definitions/${entityType}/${id}?before=${detail.next_cursor}`);setDetail(old=>old?{...old,history:[...old.history,...r.history],next_cursor:r.next_cursor}:r);}catch(e){setError((e as Error).message);}}
 return <Modal title={detail?fullName(detail.definition):'词库详情'} busy={busy} onClose={onClose}><PageError error={error} retry={()=>void load()}/>{!detail?<p role="status">正在读取词义与影响…</p>:<>
  <TabList id="definition-detail" label="词条详情" value={tab} onChange={v=>{if(!busy){setTab(v);setEditing(false);}}} items={[{key:'definition',label:'词义'},{key:'bindings',label:`绑定档案 · ${detail.counts.archives}`},{key:'history',label:'定义历史'}]}/>
  <div className="definition-panel" role="tabpanel" id="definition-detail-timeline" aria-labelledby={`definition-detail-tab-${tab}`}>
   {tab==='definition'&&(editing?<DefinitionForm entityType={entityType} definition={detail.definition} busy={busy} setBusy={setBusy} onSaved={()=>{setEditing(false);setRevision(n=>n+1);onChanged();}}/>:<><p className="tag-description">{detail.definition.description||'暂无类别说明'}</p><p className="secondary-copy">{detail.counts.open} 个开启档案 · {detail.counts.closed} 个关闭档案{!detail.definition.enabled?' · 已停用':''}</p>{detail.definition.merged_into&&<button className="button quiet" onClick={()=>setRelated(detail.definition.merged_into!)}>查看合并去向</button>}<div className="definition-actions"><button className="button" onClick={()=>setEditing(true)}>更名或澄清词义</button>{entityType==='tag'&&<button className="button quiet" onClick={()=>setOperation('meaning_change')}>迁移到新词义</button>}</div>{detail.can_administer&&<details className="definition-admin"><summary>管理员操作</summary>{entityType==='tag'&&<button className="button" onClick={()=>setOperation('merge')}>合并重复标签</button>}<button className="button quiet" onClick={()=>setOperation('availability')}>{detail.definition.enabled?'停用':'恢复'}{entityType==='tag'?'词条':'类别'}</button></details>}</>)}
   {tab==='bindings'&&<DefinitionBindings key={revision} entityType={entityType} id={id}/>}
   {tab==='history'&&<div className="definition-history">{detail.history.map(h=><article key={h.version}><small>版本 {h.version} · {h.actor_name} · {new Date(h.created_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</small><h3>{fullName(h.definition)}</h3><p>{h.definition.description}</p>{h.definition.reason&&<p className="secondary-copy">{h.definition.reason}</p>}</article>)}{detail.next_cursor&&<button className="button" onClick={()=>void history()}>读取更早定义</button>}</div>}
  </div>
  {operation==='availability'&&<AvailabilityDialog entityType={entityType} definition={detail.definition} onClose={()=>setOperation(null)} onSaved={()=>{setOperation(null);setRevision(n=>n+1);onChanged();}}/>}
  {(operation==='meaning_change'||operation==='merge')&&<MigrationDialog mode={operation} source={detail.definition} onClose={()=>setOperation(null)} onSaved={()=>{setOperation(null);setRevision(n=>n+1);onChanged();}}/>}
 </>}{related&&<TagDefinitionDialog entityType="tag" id={related} onClose={()=>setRelated(null)} onChanged={onChanged}/>}</Modal>;
}
function DefinitionBindings({entityType,id}:{entityType:'tag'|'category';id:string}){
 type Bound={id:string;name:string;closed:boolean;url:string;tags:TagBinding[]};
 const[group,setGroup]=useState('open'),[rows,setRows]=useState<Bound[]>([]),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),serial=useRef(0);
 async function load(before?:string){const n=++serial.current;setLoading(true);try{const r=await api<{archives:Bound[];next_cursor:string|null}>(`/tag-bindings/${entityType}/${id}?`+new URLSearchParams({closed:group,...(before?{before}:{})}));if(n===serial.current){setRows(old=>before?[...old,...r.archives]:r.archives);setCursor(r.next_cursor);setError('');}}catch(e){if(n===serial.current)setError((e as Error).message);}finally{if(n===serial.current)setLoading(false);}}
 useEffect(()=>{setRows([]);void load();return()=>{serial.current++;};},[group,id]);
 return <div className="definition-bindings"><label>档案范围<select value={group} onChange={e=>setGroup(e.target.value)}><option value="open">开启中</option><option value="closed">已关闭</option><option value="all">全部</option></select></label><PageError error={error} retry={()=>void load()}/>{rows.map(a=><article key={a.id}><a href={a.url}>{a.name} ↗</a>{a.closed&&<small>已关闭 · 保留当时词义</small>}{a.tags.map(tag=><details key={tag.tag_id}><summary><TagChip tag={tag}/> 查看依据</summary><TagEvidence items={tag.evidence}/></details>)}</article>)}{loading?<p role="status">正在读取绑定…</p>:cursor?<button className="button" onClick={()=>void load(cursor)}>更多绑定档案</button>:!rows.length&&<p className="secondary-copy">此范围内没有可见绑定。</p>}</div>;
}
function DefinitionForm({entityType,definition:d,busy,setBusy,onSaved}:{entityType:'tag'|'category';definition:Definition;busy:boolean;setBusy:(v:boolean)=>void;onSaved:()=>void}){
 const[name,setName]=useState(d.name),[description,setDescription]=useState(d.description),[category,setCategory]=useState(d.category_id??''),[color,setColor]=useState(d.color),[reason,setReason]=useState(''),[categories,setCategories]=useState<Definition[]>([]),[error,setError]=useState(''),[preview,setPreview]=useState<Impact|null>(null),request=useRef<string|null>(null);
 useEffect(()=>{if(entityType==='tag')api<{categories:Definition[]}>('/tag-categories?type='+d.type).then(r=>setCategories(r.categories)).catch(e=>setError(e.message));},[d.type,entityType]);
 const change={entity_type:entityType,id:d.id,name,description,reason,...(entityType==='tag'?{category_id:category}:{color})};
 async function inspect(e?:FormEvent){e?.preventDefault();setBusy(true);setError('');try{setPreview(await api<Impact>('/tag-definitions/preview',change));request.current=crypto.randomUUID();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!preview)return;setBusy(true);setError('');try{await api('/tag-definitions/apply',{preview_id:preview.preview_id,request_id:request.current});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(preview)return <div className="definition-impact"><h3>修改影响</h3>{preview.diff.length?<dl>{preview.diff.map(diff=><React.Fragment key={diff.field}><dt>{fields[diff.field]}</dt><dd><del>{diff.field==='category_id'?d.category_name:String(diff.before)}</del><span> → </span><strong>{diff.field==='category_id'?categories.find(c=>c.id===diff.after)?.name:String(diff.after)}</strong></dd></React.Fragment>)}</dl>:<p>定义没有变化。</p>}<p>{preview.counts.open} 个开启档案将采用新定义。{preview.counts.closed} 个关闭档案保留原文。</p><PageError error={error} retry={()=>void inspect()} retryLabel="重新预览当前影响"/><ModalActions><button className="button" disabled={busy} onClick={()=>setPreview(null)}>返回修改</button><button className="button primary" disabled={busy} onClick={()=>void save()}>{busy?'正在保存…':'确认保存定义'}</button></ModalActions></div>;
 return <form className="manage-form definition-form" onSubmit={inspect}><p className="secondary-copy">用于澄清同一特征。含义改变时请新建词条，再明确选择要迁移的档案。</p><label>名称<input required maxLength={entityType==='tag'?40:24} value={name} onChange={e=>setName(e.target.value)}/></label><label>通用释义<textarea required={entityType==='tag'} maxLength={160} rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label>{entityType==='tag'?<label>类别<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.filter(c=>c.enabled||c.id===d.category_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:<label>类别颜色<select value={color} onChange={e=>setColor(e.target.value)}>{Object.entries({sage:'浅绿',blue:'浅蓝',sand:'沙色',lavender:'浅紫',slate:'灰蓝',peach:'桃色',teal:'青绿'}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}<label>修改原因<input required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><PageError error={error}/><ModalActions><button className="button primary" disabled={busy}>{busy?'正在核对影响…':'查看修改影响'}</button></ModalActions></form>;
}

function AvailabilityDialog({entityType,definition:d,onClose,onSaved}:{entityType:'tag'|'category';definition:Definition;onClose:()=>void;onSaved:()=>void}){
 const[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<{preview_id:string;counts:Counts;notice:string}|null>(null),request=useRef<string|null>(null),verb=d.enabled?'停用':'恢复';
 async function inspect(e?:FormEvent){e?.preventDefault();setBusy(true);setError('');try{setPreview(await api('/tag-availability/preview',{entity_type:entityType,id:d.id,enabled:!d.enabled,reason}));request.current=crypto.randomUUID();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{await api('/tag-availability/apply',{preview_id:preview!.preview_id,request_id:request.current});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={verb+fullName(d)} busy={busy} onClose={onClose}>{preview?<div className="definition-impact"><p>{preview.notice}</p><p>当前涉及 {preview.counts.open} 个开启档案、{preview.counts.closed} 个关闭档案，已有绑定均保留。</p><PageError error={error} retry={()=>void inspect()} retryLabel="重新预览当前影响"/><ModalActions><button className="button" disabled={busy} onClick={()=>setPreview(null)}>返回修改</button><button className="button primary" disabled={busy} onClick={()=>void save()}>{busy?'正在保存…':'确认'+verb}</button></ModalActions></div>:<form className="manage-form" onSubmit={inspect}><label>{verb}原因<textarea required rows={3} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><PageError error={error}/><ModalActions><button className="button primary" disabled={busy}>{busy?'正在核对影响…':'查看修改影响'}</button></ModalActions></form>}</Modal>;
}
function MigrationDialog({mode,source,onClose,onSaved}:{mode:'meaning_change'|'merge';source:Definition;onClose:()=>void;onSaved:()=>void}){
 type Bound={id:string;name:string;version:number;tags:TagBinding[]};
 type Preview={preview_id:string;selected:{archive_id:string;name:string;target_already_bound:boolean;evidence_count:number}[];remaining_open:number;preserved_closed:number;notice:string};
 const[target,setTarget]=useState<Definition|null>(null),[rows,setRows]=useState<Bound[]>([]),[cursor,setCursor]=useState<string|null>(null),[selected,setSelected]=useState<Record<string,string>>({}),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[completed,setCompleted]=useState<{completed:unknown[];remaining_open:number;preserved_closed:number}|null>(null),request=useRef<string|null>(null);
 async function load(before?:string){setLoading(true);setError('');try{const r=await api<{archives:Bound[];next_cursor:string|null}>(`/tag-bindings/tag/${source.id}?closed=open`+(before?'&before='+before:''));setRows(old=>before?[...old,...r.archives]:r.archives);setCursor(r.next_cursor);if(!before)setSelected(old=>Object.fromEntries(Object.entries(old).filter(([id])=>r.archives.some(a=>a.id===id))));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[source.id]);
 async function choose(id:string){const r=await api<Detail>('/tag-definitions/tag/'+id);setTarget(r.definition);}
 async function inspect(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{setPreview(await api<Preview>('/tag-migration/preview',{mode,from_tag_id:source.id,to_tag_id:target!.id,reason,archives:rows.filter(a=>Object.hasOwn(selected,a.id)).map(a=>({archive_id:a.id,expected_version:a.version,...(mode==='meaning_change'?{evidence:[{kind:'member_instruction',note:selected[a.id]}]}:{})}))}));request.current=crypto.randomUUID();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{setCompleted(await api('/tag-migration/apply',{preview_id:preview!.preview_id,request_id:request.current}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const title=mode==='merge'?'合并重复标签':'迁移到新词义';
 return <Modal title={title} busy={busy} onClose={completed?onSaved:onClose}>{completed?<div className="definition-impact"><h3>本批已完成</h3><p>已迁移 {completed.completed.length} 个档案。尚有 {completed.remaining_open} 个开启档案保留来源绑定，{completed.preserved_closed} 个关闭档案保留快照。</p><ModalActions><button className="button primary" onClick={onSaved}>完成</button></ModalActions></div>:!target?<><p className="secondary-copy">来源：{fullName(source)}。{mode==='merge'?'选择要保留的同义标签。':'选择或新建准确表达新特征的标签。'}</p><TagChooser type={source.type} boundIds={[source.id]} allowCreate={mode==='meaning_change'} selectLabel="选择" onSelect={choose}/></>:preview?<div className="definition-impact"><h3>{fullName(source)} → {fullName(target)}</h3><p>{preview.notice}</p><ul>{preview.selected.map(a=><li key={a.archive_id}>{a.name}{a.target_already_bound?' · 目标已绑定，合并依据':''} · {a.evidence_count} 条依据</li>)}</ul><p>{preview.remaining_open} 个未选开启档案、{preview.preserved_closed} 个关闭档案保留来源绑定。</p><PageError error={error} retry={()=>{setPreview(null);void load();}} retryLabel="重新读取绑定后预览"/><ModalActions><button className="button" disabled={busy} onClick={()=>setPreview(null)}>返回选择</button><button className="button primary" disabled={busy} onClick={()=>void save()}>{busy?'正在提交…':'确认本批迁移'}</button></ModalActions></div>:<form className="manage-form migration-form" onSubmit={inspect}><div className="migration-target"><strong>{fullName(target)}</strong><p>{target.description}</p><button type="button" className="button quiet" onClick={()=>setTarget(null)}>重新选择目标</button></div><p className="secondary-copy">选择本批开启档案（最多 10 个）。{mode==='meaning_change'?'逐项填写支持新词义的依据。':'目标已绑定时合并依据，保留目标重点。'}</p><div className="migration-archives">{rows.map(a=><fieldset key={a.id}><label className="migration-choice"><input type="checkbox" checked={Object.hasOwn(selected,a.id)} disabled={!Object.hasOwn(selected,a.id)&&Object.keys(selected).length>=10} onChange={e=>setSelected(old=>{const next={...old};if(e.target.checked)next[a.id]='';else delete next[a.id];return next;})}/>{a.name}</label><details><summary>查看原依据</summary>{a.tags.map(tag=><TagEvidence key={tag.tag_id} items={tag.evidence}/>)}</details>{mode==='meaning_change'&&Object.hasOwn(selected,a.id)&&<label>支持新词义的依据<textarea required rows={3} maxLength={2000} value={selected[a.id]} onChange={e=>setSelected(old=>({...old,[a.id]:e.target.value}))}/></label>}</fieldset>)}</div>{loading?<p role="status">正在读取绑定…</p>:cursor?<button type="button" className="button" onClick={()=>void load(cursor)}>更多开启档案</button>:!rows.length&&<p className="secondary-copy">没有可见的开启绑定。</p>}<label>迁移原因<input required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><PageError error={error} retry={()=>void load()} retryLabel="重新读取绑定"/><ModalActions><button className="button primary" disabled={busy||loading||(mode==='meaning_change'&&!Object.keys(selected).length)}>{busy?'正在核对影响…':'查看迁移影响'}</button></ModalActions></form>}</Modal>;
}
