import {CaughtUp,UpdateRow,WorkspaceFrame} from '../ui/Workspace';
import {Avatar} from './Avatar';
import {avatarUrl} from './AvatarEditor';
import {groupActivities} from '../shared/activity-groups';
import React,{useEffect,useRef,useState} from 'react';
import {api,type Member} from './api';
import {ArchivesPage} from './ArchivesPage';
import {PageError} from './ConnectionPages';
type Entry={actor_id:string;id:string;seq:number;archive_id:string;archive_name:string;type:'person'|'org';closed:number;kind:string;actor_name:string;created_at:string;read?:boolean};
const kinds:Record<string,string>={'material.uploaded':'新增材料','material.updated':'材料更新','material.deleted':'材料已删除','material.restored':'材料已恢复','material.purged':'材料已清除','material.capacity_changed':'材料容量调整','observation.created':'新的观察','observation.edited':'观察已编辑','observation.deleted':'观察已删除','observation.restored':'观察已恢复','archive.created':'新建档案','archive.profile_changed':'资料更新','archive.tags_changed':'标签变化','archive.state_changed':'状态变化','archive.members_changed':'成员变化','archive.closed':'档案已关闭','archive.reopened':'档案已开启','archive.avatar_changed':'头像更新'};
export function UnreadBadge({onCount}:{onCount?:(total:number)=>void}={}){
 const[total,setTotal]=useState<number|null>(null);
 useEffect(()=>{let cancelled=false,timer:ReturnType<typeof setTimeout>;const load=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(document.visibilityState==='visible')void api<{total:number}>('/reading').then(r=>{if(!cancelled){setTotal(r.total);onCount?.(r.total);}}).catch(()=>{});},500);};load();window.addEventListener('cts-reading-confirmed',load);document.addEventListener('visibilitychange',load);return()=>{cancelled=true;clearTimeout(timer);window.removeEventListener('cts-reading-confirmed',load);document.removeEventListener('visibilitychange',load);};},[onCount]);
 return <>{total!==null&&total>0&&<span className="nav-unread">{total}</span>}</>;
}
export function UnreadPage({actor}:{actor:Member}){
 const[items,setItems]=useState<Entry[]>([]),[selected,setSelected]=useState<string|null>(null),[cursor,setCursor]=useState<string|null>(null),[snapshot,setSnapshot]=useState<number|undefined>(),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const serial=useRef(0),current=items.find(e=>e.id===selected),remaining=items.filter(e=>!e.read),complete=!loading&&!error&&!cursor&&items.length>0&&!remaining.length;
 async function load(before?:string,selectNext=false){const n=++serial.current;setLoading(true);setError('');try{const r=await api<{events:Entry[];snapshot:number;next_cursor:string|null}>('/reading/events?'+new URLSearchParams({...(before?{before,snapshot:String(snapshot)}:{})}));if(n!==serial.current)return;setItems(old=>before?[...old,...r.events.filter(e=>!old.some(existing=>existing.id===e.id))]:r.events);setSnapshot(r.snapshot);setCursor(r.next_cursor);if(!before||selectNext)setSelected(r.events[0]?.id??null);}catch(e){if(n===serial.current)setError((e as Error).message);}finally{if(n===serial.current)setLoading(false);}}
 useEffect(()=>{void load();const read=(event:Event)=>{const ids=(event as CustomEvent<string[]>).detail;setItems(old=>old.map(e=>ids.includes(e.id)?{...e,read:true}:e));};window.addEventListener('cts-reading-confirmed',read);return()=>{serial.current++;window.removeEventListener('cts-reading-confirmed',read);};},[actor.id]);
 async function next(){const available=remaining.filter(e=>e.id!==selected),same=available.find(e=>e.archive_id===current?.archive_id);if(same){setSelected(same.id);return;}setLoading(true);setError('');try{if(cursor&&current){const r=await api<{events:Entry[]}>('/reading/events?'+new URLSearchParams({archive_id:current.archive_id,exclude_event_id:current.id,snapshot:String(snapshot),limit:'1'}));if(r.events.length){const target=r.events[0];setItems(old=>old.some(e=>e.id===target.id)?old:[...old,target]);setSelected(target.id);return;}}if(available[0])setSelected(available[0].id);else if(cursor)await load(cursor,true);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 return <WorkspaceFrame selected={!!current} list={<>
  <header className="page-head"><div><h1>未读更新</h1></div><button className="button" disabled={loading} onClick={()=>void load()}>刷新队列</button></header>
  <div className="unread-progress"><span>{items.filter(e=>e.read).length} / {items.length}{cursor?'＋':''} 已阅</span><button className="text-button" disabled={loading||(!remaining.some(e=>e.id!==selected)&&!cursor)} onClick={()=>void next()}>下一处未读 →</button></div>
  <PageError error={error} retry={()=>void load(items.length&&cursor?cursor:undefined)}/>
  <section className="updates-list" aria-label="本次未读队列"><p className="section-description">从变化的地方读起。已阅条目保留在本次位置。</p>
  {!loading&&!error&&(!items.length||complete)?<CaughtUp action={<button className="button outline" onClick={()=>{history.pushState(null,'','/');window.dispatchEvent(new PopStateEvent('popstate'));}}>回到人物档案</button>}/>:groupActivities(items).map(group=>{const first=group.events[0],unread=group.events.filter(e=>!e.read);return <React.Fragment key={group.id}><UpdateRow selected={group.events.some(e=>e.id===selected)} onClick={()=>setSelected((unread[0]??first).id)} avatar={<Avatar name={first.archive_name} type={first.type} src={avatarUrl('archive',first.archive_id,0)}/>} label={<>{first.type==='person'?'人物':'组织'} · {unread.length?`${unread.length} 项更新`:'已阅'}{first.closed?' · 已关闭':''}</>} name={first.archive_name} excerpt={[...new Set(group.events.map(e=>kinds[e.kind]??'档案更新'))].join('、')} time={`${first.actor_name} · ${new Date(first.created_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})}`} read={!unread.length}/>{group.events.length>1&&<details className="unread-batch-details"><summary>{group.events.length} 项操作 · 展开明细</summary>{group.events.map(e=><button key={e.id} aria-current={e.id===selected} onClick={()=>setSelected(e.id)}>{kinds[e.kind]??'档案更新'} · {e.read?'已阅':'未读'}</button>)}</details>}</React.Fragment>;})}
  </section>{loading?<p className="stream-status" role="status">正在读取更新…</p>:cursor&&<button className="button archive-load" onClick={()=>void load(cursor)}>加载更多更新</button>}
 </>} detail={current?<ArchivesPage key={current.archive_id} actor={actor} type={current.type} detailOnly onNextUnread={remaining.some(e=>e.id!==selected)||cursor?()=>void next():undefined} onClose={()=>setSelected(null)} linked={{archiveId:current.archive_id,focus:{event_id:current.id,key:current.id}}}/>:<aside className="selection-rest"><span>选择一条更新，继续观察。</span></aside>}/>;
}
