import React,{useEffect,useState,type CSSProperties,type FormEvent} from 'react';
import {api,type Member} from './api';
import {PageError} from './ConnectionPages';
import {Modal,ModalActions} from './Modal';
import {Avatar} from './Avatar';
import {avatarUrl} from './AvatarEditor';
import './work-tasks.css';

type Scope='all'|'recommended'|'mine'|'admin';
type TaskState='open'|'closed';
export type ArchivePreview={id:string;type:'person'|'org';name:string;status:string;version:number;updated_at:string;observation_count:number;latest_observation:string|null;members:{id:string;name:string;frozen:boolean}[];tag_summary:{tags:{tag_id:string;category_name:string;name:string;color:string;focus:number}[];total:number}};
type Task={id:string;archive_id:string|null;archive_preview?:ArchivePreview;kind:'audit'|'onboarding'|'monthly'|'cooperation'|'custom';title:string;purpose:string;delivery:string;status:'open'|'completed'|'expired'|'cancelled';owner_id:string|null;owner_name?:string|null;created_by:string;deadline_at:string;created_at:string;version:number;result_kind?:string|null;result_text?:string|null;result_references?:{observation_id:string;archive_id:string;content_version:number}[];result_references_restricted?:boolean;completed_at?:string|null;closed_reason?:string|null;candidate_count?:number;push_stage?:string};
type ObservationOption={id:string;content_version:number;author_name:string;created_at:string;body:string;deleted:boolean};
const labels:Record<Task['kind'],string>={audit:'人事审核',onboarding:'入社对接',monthly:'月度沟通',cooperation:'组织合作',custom:'临时工作'};
const stageLabels:Record<string,string>={initial:'首次推送',reminder:'三日提醒',admin:'管理员队列'};
const statusLabels:Record<Task['status'],string>={open:'进行中',completed:'已完成',expired:'已过期',cancelled:'已取消'};
const deadlineDefault=()=>new Date(Date.now()+7*86400000).toISOString().slice(0,16);
const iso=(value:string)=>new Date(value).toISOString();
const displayDate=(value:string)=>new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false,month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const purposeDefault='说明本次要处理的对象、判断或行动。';
const deliveryDefault='结果写回关联档案；没有关联档案时，在任务结果中交代。';

function ArchivePeek({archive,onOpen}:{archive:ArchivePreview;onOpen:(archive:ArchivePreview)=>void}){
 const[open,setOpen]=useState(false),timer=React.useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const later=(next:boolean)=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setOpen(next),next?90:150);};
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const tags=archive.tag_summary.tags.slice(0,3);
 return <span className="task-archive-anchor" onMouseEnter={()=>later(true)} onMouseLeave={()=>later(false)}>
  <button className="task-archive-link" type="button" onFocus={()=>later(true)} onBlur={()=>later(false)} onClick={()=>onOpen(archive)} aria-haspopup="dialog" aria-expanded={open}>
   <Avatar name={archive.name} type={archive.type} size="micro" src={avatarUrl('archive',archive.id,archive.version)}/>
   <span className="task-archive-copy"><strong>{archive.name}</strong><small>{archive.status}</small></span>
  </button>
  {open&&<aside className="archive-peek" role="dialog" aria-label={`${archive.name}档案速览`} onFocus={()=>later(true)} onMouseEnter={()=>later(true)} onMouseLeave={()=>later(false)}>
   <header><Avatar name={archive.name} type={archive.type} size="tiny" src={avatarUrl('archive',archive.id,archive.version)}/><div><strong>{archive.name}</strong><span>{archive.status}</span></div><button className="archive-peek-close" type="button" aria-label="关闭速览" onClick={()=>setOpen(false)}>×</button></header>
   {tags.length>0&&<div className="archive-peek-tags">{tags.map(tag=><span key={tag.tag_id} style={{'--tag-color':tag.color} as CSSProperties}>{tag.category_name}：{tag.name}</span>)}</div>}
   <p>{archive.latest_observation??'还没有观察记录。'}</p>
   <footer><small>{archive.observation_count} 条观察</small><button type="button" className="text-button" onClick={()=>onOpen(archive)}>打开档案</button></footer>
  </aside>}
 </span>;
}

function CreateTask({onSaved}:{onSaved:()=>void}){
 const[open,setOpen]=useState(false),[kind,setKind]=useState<Task['kind']>('custom'),[title,setTitle]=useState(labels.custom),[purpose,setPurpose]=useState(''),[delivery,setDelivery]=useState(deliveryDefault),[deadline,setDeadline]=useState(deadlineDefault),[error,setError]=useState(''),[busy,setBusy]=useState(false),[advanced,setAdvanced]=useState(false);
 useEffect(()=>{if(!title)setTitle(labels[kind]);},[kind]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/work-tasks/create',{kind,title,purpose:purpose||purposeDefault,delivery,deadline_at:iso(deadline),request_id:crypto.randomUUID()});onSaved();setOpen(false);setTitle(labels[kind]);setPurpose('');setDelivery(deliveryDefault);setDeadline(deadlineDefault());setAdvanced(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <>{<button className="button primary work-task-create-button" onClick={()=>{setError('');setOpen(true);}}>新建任务</button>}{open&&<Modal title="新建任务" busy={busy} onClose={()=>setOpen(false)}><form className="manage-form modal-form work-task-create" onSubmit={submit}><label>类型<select value={kind} onChange={e=>{const next=e.target.value as Task['kind'];setKind(next);if(!title||Object.values(labels).includes(title))setTitle(labels[next]);}}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>标题<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>要处理什么<textarea required maxLength={4000} rows={4} value={purpose} placeholder={purposeDefault} onChange={e=>setPurpose(e.target.value)}/></label><p className="task-defaults">默认交付：{deliveryDefault}<br/>默认接取期限：7 天</p><details className="task-advanced" open={advanced} onToggle={e=>setAdvanced(e.currentTarget.open)}><summary>调整交付和期限</summary><label>交付要求<textarea required maxLength={4000} rows={3} value={delivery} onChange={e=>setDelivery(e.target.value)}/></label><label>接取期限<input required type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label></details><PageError error={error}/><ModalActions><button className="button primary" disabled={busy}>{busy?'正在创建…':'创建任务'}</button></ModalActions></form></Modal>}</>;
}

function CompleteForm({task,onSaved}:{task:Task;onSaved:()=>void}){
 const[kind,setKind]=useState('completed'),[text,setText]=useState(''),[references,setReferences]=useState<{observation_id:string;content_version:number}[]>([]),[observations,setObservations]=useState<ObservationOption[]>([]),[cursor,setCursor]=useState<string|null>(null),[loadingReferences,setLoadingReferences]=useState(false),[error,setError]=useState(''),[referenceError,setReferenceError]=useState(''),[busy,setBusy]=useState(false);
 async function loadReferences(before?:string){if(!task.archive_id)return;setLoadingReferences(true);setReferenceError('');try{const r=await api<{observations:ObservationOption[];next_cursor:string|null}>('/observations?'+new URLSearchParams({archive_id:task.archive_id,deleted:'false',limit:'20',...(before?{before}:{})}));setObservations(old=>before?[...old,...r.observations.filter(o=>!o.deleted)]:r.observations.filter(o=>!o.deleted));setCursor(r.next_cursor);}catch(e){setReferenceError((e as Error).message);}finally{setLoadingReferences(false);}}
 useEffect(()=>{setObservations([]);setCursor(null);void loadReferences();},[task.archive_id]);
 function toggleReference(observation:ObservationOption){setReferences(current=>current.some(ref=>ref.observation_id===observation.id)?current.filter(ref=>ref.observation_id!==observation.id):[...current,{observation_id:observation.id,content_version:observation.content_version}]);}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/work-tasks/complete',{id:task.id,expected_version:task.version,result_kind:kind,result_text:text,references,request_id:crypto.randomUUID()});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="work-task-result" onSubmit={submit}><label>完成结果<select value={kind} onChange={e=>setKind(e.target.value)}><option value="completed">已完成</option><option value="continue">建议继续</option><option value="unable_to_contact">暂未联系到</option><option value="not_suitable">不再继续</option></select></label><label>结果说明<textarea required rows={3} maxLength={5000} value={text} onChange={e=>setText(e.target.value)} placeholder="如实交代做了什么、结果是什么、还需要什么"/></label>{task.archive_id&&<fieldset className="task-result-references"><legend>引用已有观察（可选）</legend>{loadingReferences&&!observations.length?<p className="history-loading">正在读取观察…</p>:observations.length?observations.map(observation=><label key={observation.id}><input type="checkbox" checked={references.some(ref=>ref.observation_id===observation.id)} onChange={()=>toggleReference(observation)}/><span><strong>{observation.author_name}</strong> · {displayDate(observation.created_at)}<small>{observation.body.slice(0,160)||'（图片观察）'}</small></span></label>):<p className="history-loading">暂无可引用的观察</p>}{referenceError&&<PageError error={referenceError} retry={()=>void loadReferences(cursor??undefined)}/>} {loadingReferences&&observations.length>0&&<p className="history-loading">正在读取更多观察…</p>}{!loadingReferences&&cursor&&<button type="button" className="text-button" onClick={()=>void loadReferences(cursor)}>加载更早观察</button>}</fieldset>}<PageError error={error}/><button className="button primary" disabled={busy}>{busy?'正在提交…':'提交结果并结束任务'}</button></form>;
}

const taskUi={member:'\u6210\u5458',system:'\u7cfb\u7edf',edit:'\u7f16\u8f91',remove:'\u5220\u9664',restore:'\u6062\u590d',deleted:'\u8bc4\u8bba\u5df2\u5220\u9664',hidden:'\u90e8\u5206\u89c2\u5bdf\u5f15\u7528\u5f53\u524d\u4e0d\u53ef\u89c1',editPrompt:'\u4fee\u6539\u8bc4\u8bba',confirmDelete:'\u5220\u9664\u540e\u4ecd\u53ef\u6062\u590d\uff0c\u7ee7\u7eed\u5417\uff1f',hideHistory:'\u6536\u8d77\u5386\u53f2',showHistory:'\u67e5\u770b\u64cd\u4f5c\u5386\u53f2\u4e0e\u8bc4\u8bba',loading:'\u6b63\u5728\u8bfb\u53d6\u2026',comments:'\u5de5\u4f5c\u8bc4\u8bba',placeholder:'\u8bb0\u5f55\u8fdb\u5c55\u3001\u56f0\u96be\u6216\u4e0b\u4e00\u6b65',saving:'\u6b63\u5728\u4fdd\u5b58\u2026',add:'\u53d1\u8868\u8bc4\u8bba',readonly:'\u4efb\u52a1\u5df2\u5173\u95ed\uff0c\u5386\u53f2\u53ea\u8bfb\uff1b\u91cd\u65b0\u5f00\u542f\u540e\u53ef\u7ee7\u7eed\u8ba8\u8bba'};
const taskUiExtended={versionHistory:'编辑历史',references:'引用观察',change:'变更'};
type TaskEvent={kind:string;actor_name?:string|null;reason?:string|null;created_at:string;before_json?:string|null;after_json?:string|null};
type CommentVersion={version:number;body:string|null;deleted:boolean;deleted_at?:string|null;references:{observation_id:string;archive_id:string;content_version:number}[];references_restricted?:boolean;actor_id?:string|null;source?:string;created_at:string};
type TaskComment={id:string;task_id:string;author_id:string;author_name?:string|null;body:string|null;references:{observation_id:string;archive_id:string;content_version:number}[];history:CommentVersion[];created_at:string;updated_at:string;deleted:boolean;version:number;references_restricted?:boolean};
const eventLabels:Record<string,string>={created:'创建任务',claimed:'领取任务',assigned:'指派任务',released:'交还任务',cancelled:'取消任务',edited:'修改任务',deadline_changed:'延长截止时间',reopened:'重新开启任务',expired:'任务到期',completed:'提交结果并完成',comment_created:'发表评论',comment_updated:'编辑评论',comment_deleted:'删除评论',comment_restored:'恢复评论'};
const fieldLabels:Record<string,string>={title:'标题',purpose:'目的',delivery:'交付要求',deadline_at:'截止时间',owner_id:'负责人',status:'状态',result_kind:'结果类型',result_text:'结果说明',version:'版本',reference_count:'引用数量',comment_id:'评论'};
function parseEvent(value:string|null|undefined){if(!value)return null;try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'?parsed as Record<string,unknown>:null;}catch{return null;}}
function eventValue(key:string,value:unknown){if(value===null||value===undefined||value==='')return '无';if(key==='deadline_at'&&typeof value==='string')return displayDate(value);if(key==='owner_id')return typeof value==='string'?value.slice(0,8):'无人负责';if(key==='status'){const labels:Record<string,string>={open:'进行中',completed:'已完成',expired:'已过期',cancelled:'已取消'};return labels[String(value)]??String(value);}return String(value);}
function eventChanges(event:TaskEvent){const before=parseEvent(event.before_json),after=parseEvent(event.after_json);if(!before&&!after)return [];const keys=[...new Set([...Object.keys(before??{}),...Object.keys(after??{})])].filter(key=>!['version','comment_id','reference_count'].includes(key));return keys.filter(key=>JSON.stringify(before?.[key])!==JSON.stringify(after?.[key])).map(key=>({key,before:eventValue(key,before?.[key]),after:eventValue(key,after?.[key])}));}
function TaskCommentItem({item,task,actor,busy,onEdit,onDelete,onRestore,onReference}:{item:TaskComment;task:Task;actor:Member;busy:boolean;onEdit:(item:TaskComment)=>void;onDelete:(item:TaskComment)=>void;onRestore:(item:TaskComment)=>void;onReference:(reference:{observation_id:string;archive_id:string;content_version:number})=>void}){
 const canChange=item.author_id===actor.id||actor.role==='admin';
 return <article className="work-task-comment"><header><strong>{item.author_name??taskUi.member}</strong><time>{displayDate(item.created_at)}</time></header>{item.deleted&&item.body===null?<p className="comment-deleted">{taskUi.deleted}</p>:<><p>{item.body}</p>{item.references.length>0&&<div className="task-comment-references"><small>{taskUiExtended.references}</small>{item.references.map(reference=><button type="button" className="text-button" key={reference.observation_id+'-'+reference.content_version} onClick={()=>onReference(reference)}>观察版本 {reference.content_version}</button>)}</div>}{item.references_restricted&&<small className="comment-reference-hidden">{taskUi.hidden}</small>}</>} {item.history.length>1&&<details className="task-comment-history"><summary>{taskUiExtended.versionHistory}（{item.history.length}）</summary><ol>{item.history.map(version=><li key={version.version}><header><strong>版本 {version.version}</strong><time>{displayDate(version.created_at)}</time></header>{version.body===null?<p className="comment-deleted">{taskUi.deleted}</p>:<p>{version.body}</p>}{version.references.length>0&&<small>{taskUiExtended.references} {version.references.map(reference=>`观察版本 ${reference.content_version}`).join('、')}</small>}{version.references_restricted&&<small className="comment-reference-hidden">{taskUi.hidden}</small>}</li>)}</ol></details>}<footer>{!item.deleted&&canChange&&<button type="button" className="text-button" disabled={busy||task.status!=='open'} onClick={()=>onEdit(item)}>{taskUi.edit}</button>}{!item.deleted&&canChange&&<button type="button" className="text-button" disabled={busy||task.status!=='open'} onClick={()=>onDelete(item)}>{taskUi.remove}</button>}{item.deleted&&canChange&&<button type="button" className="text-button" disabled={busy||task.status!=='open'} onClick={()=>onRestore(item)}>{taskUi.restore}</button>}</footer></article>;
}
function TaskHistory({task,actor,onOpenArchive}:{task:Task;actor:Member;onOpenArchive:(archive:ArchivePreview,taskId:string,observationId?:string,contentVersion?:number)=>void}){
 const[open,setOpen]=useState(false),[events,setEvents]=useState<TaskEvent[]>([]),[comments,setComments]=useState<TaskComment[]>([]),[comment,setComment]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await api<{events:TaskEvent[];comments:TaskComment[]}>('/work-tasks/'+task.id);setEvents(r.events);setComments(r.comments);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function toggle(){if(open){setOpen(false);return;}setOpen(true);if(!events.length&&!comments.length)await load();}
 async function add(e:FormEvent){e.preventDefault();if(!comment.trim())return;setBusy(true);setError('');try{await api('/work-tasks/comments/create',{task_id:task.id,body:comment.trim(),request_id:crypto.randomUUID()});setComment('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function edit(item:TaskComment){const body=window.prompt(taskUi.editPrompt,item.body??'');if(body===null||!body.trim())return;setBusy(true);setError('');try{await api('/work-tasks/comments/edit',{id:item.id,expected_version:item.version,body:body.trim(),request_id:crypto.randomUUID()});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(item:TaskComment){if(!window.confirm(taskUi.confirmDelete))return;setBusy(true);setError('');try{await api('/work-tasks/comments/delete',{id:item.id,expected_version:item.version,request_id:crypto.randomUUID()});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function restore(item:TaskComment){setBusy(true);setError('');try{await api('/work-tasks/comments/restore',{id:item.id,expected_version:item.version,request_id:crypto.randomUUID()});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="work-task-history"><button className="text-button" onClick={()=>void toggle()}>{open?taskUi.hideHistory:taskUi.showHistory}</button>{open&&(loading?<p className="history-loading">{taskUi.loading}</p>:error?<p className="form-error">{error}</p>:<><ol>{events.map((event,index)=>{const changes=eventChanges(event);return <li key={event.created_at+'-'+index}><strong>{eventLabels[event.kind.replace('task.','')]??event.kind.replace('task.','')}</strong><span>{event.actor_name??taskUi.system} {'·'} {displayDate(event.created_at)}</span>{event.reason&&<small>{event.reason}</small>}{changes.length>0&&<details><summary>{taskUiExtended.change}</summary><ul>{changes.map(change=><li key={change.key}>{fieldLabels[change.key]??change.key}：{change.before} → {change.after}</li>)}</ul></details>}</li>})}</ol><div className="work-task-comments"><h3>{taskUi.comments}</h3>{comments.map(item=><TaskCommentItem key={item.id} item={item} task={task} actor={actor} busy={busy} onEdit={item=>void edit(item)} onDelete={item=>void remove(item)} onRestore={item=>void restore(item)} onReference={reference=>task.archive_preview&&onOpenArchive(task.archive_preview,task.id,reference.observation_id,reference.content_version)}/>)}{task.status==='open'?<form className="work-task-comment-form" onSubmit={e=>void add(e)}><textarea rows={3} maxLength={5000} value={comment} onChange={e=>setComment(e.target.value)} placeholder={taskUi.placeholder} required/><button className="button quiet" disabled={busy}>{busy?taskUi.saving:taskUi.add}</button></form>:<p className="task-scene-readonly">{taskUi.readonly}</p>}</div></>)}</section>;
}
function taskActionTitle(task:Task){
 const name=task.archive_preview?.name;
  return name&&task.title.startsWith(`${name} ${'\u00b7'} `)?task.title.slice(name.length+3):task.title;
}

function TaskIndexItem({task,actor,selected,onSelect}:{task:Task;actor:Member;selected:boolean;onSelect:()=>void}){
 const mine=task.owner_id===actor.id,soon=task.status==='open'&&Date.parse(task.deadline_at)-Date.now()<=3*86400000;
 return <button type="button" className={'task-index-item '+(selected?'selected':'')} onClick={onSelect} aria-pressed={selected}>
  <strong>{taskActionTitle(task)}</strong>
  {task.archive_preview?<span className="task-index-subject"><Avatar name={task.archive_preview.name} type={task.archive_preview.type} size="micro"/><b>{task.archive_preview.name}</b></span>:<span className="task-index-subject task-index-unlinked">未关联档案</span>}
  <footer><span className={mine?'task-index-owner mine':!task.owner_id?'task-index-owner waiting':'task-index-owner'}>{mine?'我负责':task.owner_name??'待接取'}</span><time className={soon?'soon':''}>{soon?'即将到期 · ':''}{displayDate(task.deadline_at)}</time></footer>
 </button>;
}

function TaskScene({task,actor,onChanged,onOpenArchive}:{task:Task;actor:Member;onChanged:()=>void;onOpenArchive:(archive:ArchivePreview,taskId:string,observationId?:string,contentVersion?:number)=>void}){
 const[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[flash,setFlash]=useState(''),mine=task.owner_id===actor.id;
 function changed(kind:string){setFlash(kind);onChanged();window.setTimeout(()=>setFlash(''),500);}
 async function claim(){setBusy(true);setError('');try{await api('/work-tasks/claim',{id:task.id,expected_version:task.version,request_id:crypto.randomUUID()});changed('claimed');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function release(){setBusy(true);setError('');try{await api('/work-tasks/release',{id:task.id,expected_version:task.version,deadline_at:iso(deadlineDefault()),request_id:crypto.randomUUID()});changed('released');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function cancel(){const reason=window.prompt('取消原因','这项工作不再适用');if(!reason?.trim())return;setBusy(true);setError('');try{await api('/work-tasks/cancel',{id:task.id,expected_version:task.version,reason:reason.trim(),request_id:crypto.randomUUID()});changed('cancelled');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function editTask(){const title=window.prompt('任务标题',task.title);if(title===null)return;const purpose=window.prompt('任务目的',task.purpose);if(purpose===null)return;const delivery=window.prompt('交付要求',task.delivery);if(delivery===null)return;setBusy(true);setError('');try{await api('/work-tasks/edit',{id:task.id,expected_version:task.version,title,purpose,delivery,request_id:crypto.randomUUID()});changed('edited');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function extend(){const deadline=window.prompt('新的截止时间（ISO）',iso(deadlineDefault()));if(!deadline)return;setBusy(true);setError('');try{await api('/work-tasks/extend',{id:task.id,expected_version:task.version,deadline_at:iso(deadline),reason:'负责人延长任务期限',request_id:crypto.randomUUID()});changed('extended');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function reopen(){const deadline=window.prompt('重新开启后的截止时间（ISO）',iso(deadlineDefault()));if(!deadline)return;const owner_mode=actor.role==='admin'?'unassigned':'keep';setBusy(true);setError('');try{await api('/work-tasks/reopen',{id:task.id,expected_version:task.version,deadline_at:iso(deadline),owner_mode,request_id:crypto.randomUUID()});changed('reopened');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const canEdit=task.status==='open'&&(actor.role==='admin'||task.created_by===actor.id||mine),canExtend=task.status==='open'&&mine,canCancel=task.status==='open'&&(actor.role==='admin'||task.created_by===actor.id&&!task.owner_id||mine),canReopen=(task.status==='expired'||task.status==='cancelled')&&(mine||actor.role==='admin');
 return <article className={'task-scene '+(flash?'flash-'+flash:'')}>
  <header className="task-scene-head"><div><h2>{taskActionTitle(task)}</h2><small className="task-scene-status">{statusLabels[task.status]}</small></div></header>
  <div className="task-scene-subject">{task.archive_preview?<ArchivePeek archive={task.archive_preview} onOpen={archive=>onOpenArchive(archive,task.id)}/>:<span className="task-scene-unlinked">未关联档案</span>}</div>
   <div className="task-scene-signal"><span className={'work-task-state '+(task.owner_id?'claimed':'waiting')}>{task.owner_name??(task.owner_id?'已接取':'待接取')}</span><span className="task-scene-meta">截止 {displayDate(task.deadline_at)}</span>{task.push_stage&&<span className="task-scene-meta">{stageLabels[task.push_stage]??task.push_stage}{task.candidate_count!==undefined&&(' '+ '\u00b7' +' '+task.candidate_count+' 个匹配')}</span>}</div>
  <section className="task-scene-purpose"><p>{task.purpose}</p>{task.status!=='open'&&task.result_text&&<div className="task-scene-result"><strong>结果</strong><p>{task.result_text}</p>{task.result_references?.length&&task.archive_preview&&<div className="task-result-links"><small>关联观察</small>{task.result_references.map(reference=><button type="button" className="text-button" key={reference.observation_id+'-'+reference.content_version} onClick={()=>onOpenArchive(task.archive_preview!,task.id,reference.observation_id,reference.content_version)}>观察版本 {reference.content_version}</button>)}</div>}{task.result_references_restricted&&<small className="comment-reference-hidden">部分观察引用当前不可见</small>}</div>}</section>
  <details className="task-scene-delivery"><summary>交付要求</summary><p>{task.delivery}</p></details>
  <TaskHistory task={task} actor={actor} onOpenArchive={onOpenArchive}/>
  <div className="task-scene-actions"><PageError error={error}/>{task.status==='open'&&!task.owner_id&&<button className="button primary" disabled={busy} onClick={()=>void claim()}>{busy?'正在领取…':'领取任务'}</button>}{canEdit&&<button className="button quiet" disabled={busy} onClick={()=>void editTask()}>编辑任务</button>}{canExtend&&<button className="button quiet" disabled={busy} onClick={()=>void extend()}>延期</button>}{canReopen&&<button className="button primary" disabled={busy} onClick={()=>void reopen()}>重新开启</button>}{mine&&task.status==='open'&&<><button className="button primary" disabled={busy} onClick={()=>setOpen(v=>!v)}>{open?'收起完成表单':'提交结果'}</button><button className="button quiet" disabled={busy} onClick={()=>void release()}>主动交还</button></>}{!mine&&task.owner_id&&<p className="task-scene-owner">由 {task.owner_name??'其他成员'} 负责</p>}{canCancel&&<button className="button quiet" disabled={busy} onClick={()=>void cancel()}>取消任务</button>}{open&&mine&&<CompleteForm task={task} onSaved={()=>changed('completed')}/>}</div>
 </article>;
}

export function WorkTasksPage({actor,onOpenArchive}:{actor:Member;onOpenArchive:(archive:ArchivePreview,taskId?:string,observationId?:string,contentVersion?:number)=>void}){
 const[scope,setScope]=useState<Scope>('all'),[state,setState]=useState<TaskState>('open'),[tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const[selectedId,setSelectedId]=useState<string|null>(()=>new URLSearchParams(location.search).get('task'));
 async function load(){setLoading(true);setError('');try{const r=await api<{tasks:Task[]}>('/work-tasks?'+new URLSearchParams({scope,state}));setTasks(r.tasks);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[scope,state,revision]);
 const selectedTask=tasks.find(task=>task.id===selectedId)??null;
 const updateSelection=(id:string|null)=>{setSelectedId(id);const params=new URLSearchParams(location.search);if(id)params.set('task',id);else params.delete('task');history.replaceState(null,'',location.pathname+(params.size?'?'+params.toString():''));};
 useEffect(()=>{if(loading)return;if(selectedId&&tasks.some(task=>task.id===selectedId))return;const first=tasks.find(task=>task.owner_id===actor.id)||tasks.find(task=>!task.owner_id)||tasks[0]||null;if(first)updateSelection(first.id);},[loading,selectedId,tasks,actor.id]);
 const scopes: [Scope,string][]=[['all','全部任务'],['recommended','推荐给我'],['mine','我的任务'],...(actor.role==='admin'?[['admin','管理员队列'] as [Scope,string]]:[])];
 const soon=(task:Task)=>task.status==='open'&&task.owner_id===null&&Date.parse(task.deadline_at)-Date.now()<=3*86400000;
 const groups=[{key:'attention',title:'现在需要处理',items:tasks.filter(task=>task.owner_id===actor.id||soon(task))},{key:'waiting',title:'等待接手',items:tasks.filter(task=>!task.owner_id&&!soon(task))},{key:'active',title:'其他进行中',items:tasks.filter(task=>!!task.owner_id&&task.owner_id!==actor.id)}];
 const visibleGroups=groups.filter(group=>group.items.length>0);
 return <main className="account-content work-tasks-page task-workspace"><header className="task-workspace-head"><h1>任务</h1><CreateTask onSaved={()=>setRevision(n=>n+1)}/></header><nav className="work-task-scopes" aria-label="任务范围">{scopes.map(([value,label])=><button key={value} className={scope===value?'active':''} aria-pressed={scope===value} onClick={()=>{setScope(value);updateSelection(null);}}>{label}<small>{value==='all'?tasks.length:value==='mine'?tasks.filter(task=>task.owner_id===actor.id).length:value==='recommended'?tasks.filter(task=>!task.owner_id).length:tasks.length}</small></button>)}</nav><button className={'work-task-history-toggle '+(state==='closed'?'active':'')} aria-pressed={state==='closed'} onClick={()=>{setState(v=>v==='open'?'closed':'open');updateSelection(null);}}>{state==='closed'?'打开任务':'历史'}</button><PageError error={error} retry={()=>void load()}/>{loading?<p role="status">正在读取任务…</p>:<div className={'task-workspace-grid '+(selectedTask?'has-selection':'')}><section className="task-index" aria-label="任务索引">{visibleGroups.map(group=><section className="task-index-group" key={group.key}><header><div><h2>{group.title}<span>{group.items.length}</span></h2></div></header><div className="task-index-list">{group.items.map(task=><TaskIndexItem key={task.id} task={task} actor={actor} selected={selectedId===task.id} onSelect={()=>updateSelection(task.id)}/>)}</div></section>)}{!visibleGroups.length&&<p className="task-index-empty">暂时没有任务</p>}</section>{selectedTask?<TaskScene key={selectedTask.id} task={selectedTask} actor={actor} onChanged={()=>setRevision(n=>n+1)} onOpenArchive={onOpenArchive}/>:<aside className="task-scene-empty"><span className="task-scene-empty-mark">+</span><h2>选择一项工作</h2><p>从左侧任务索引开始。</p></aside>}</div>}</main>;
}
