import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const base=process.env.BASE_URL;
if(!base)throw new Error('BASE_URL required');
const final=JSON.parse((await readFile('test-output/codex-final.json','utf8')).replace(/^\uFEFF/,''));
const {tokens}=JSON.parse((await readFile('test-credentials.json','utf8')).replace(/^\uFEFF/,''));
assert(final.success);
const headers={Authorization:`Bearer ${tokens.alice}`};
const recordResponse=await fetch(`${base}/api/entities/${final.entity_id}`,{headers});
assert.equal(recordResponse.status,200);
const snapshot=await recordResponse.json();
assert(snapshot.records.some(r=>r.id===final.record_id&&r.author_id==='alice'));
assert(snapshot.events.some(e=>e.subject_id===final.record_id&&e.source==='mcp'));
const response=await fetch(`${base}/images/${final.attachment_id}`,{headers});
assert.equal(response.status,200);
const image=Buffer.from(await response.arrayBuffer());
assert.equal(image.length,final.image_bytes);
assert.equal(createHash('sha256').update(image).digest('hex'),final.sha256);
assert.equal((await fetch(`${base}/images/${final.attachment_id}`)).status,401);
const result={at:new Date().toISOString(),...final,independentVerification:{record:true,source:'mcp',imageBytesAndHash:true,anonymousRejected:true}};
await writeFile('test-output/codex-verified.json',JSON.stringify(result,null,2));
console.log(JSON.stringify(result));
