import React,{useId,type ReactNode,type Dispatch,type SetStateAction} from 'react';
import './forms.css';
type Contact={type:string;value:string;note:string};
type Link={label:string;url:string};
export function ProfileFields({type,name,setName,contacts,setContacts,links,setLinks,children}:{type:'person'|'org';name:string;setName:(name:string)=>void;contacts:Contact[];setContacts:Dispatch<SetStateAction<Contact[]>>;links:Link[];setLinks:Dispatch<SetStateAction<Link[]>>;children?:ReactNode}){
 return <>
  <label>{type==='person'?'昵称':'组织名称'}<input required maxLength={120} autoFocus value={name} onChange={e=>setName(e.target.value)}/></label>
  {children}
  <fieldset><legend>联系方式</legend>{contacts.map((c,i)=><div className="archive-field-row" key={i}><div className="contact-main"><label><span className="visually-hidden">类型</span><select value={c.type} aria-label={`联系方式${i+1}类型`} onChange={e=>setContacts(old=>old.map((v,n)=>n===i?{...v,type:e.target.value}:v))}>{['QQ','微信','邮箱','电话','网站','其他',...(!['QQ','微信','邮箱','电话','网站','其他'].includes(c.type)?[c.type]:[])].map(v=><option key={v}>{v}</option>)}</select></label><label><span className="visually-hidden">联系方式</span><input placeholder="填写联系方式" required value={c.value} maxLength={500} aria-label={`联系方式${i+1}`} onChange={e=>setContacts(old=>old.map((v,n)=>n===i?{...v,value:e.target.value}:v))}/></label><button type="button" className="icon-close" aria-label={`移除联系方式${i+1}`} onClick={()=>setContacts(old=>old.filter((_,n)=>n!==i))}>×</button></div><details className="contact-note" open={c.note?true:undefined}><summary>备注</summary><label><span className="visually-hidden">备注</span><input value={c.note} maxLength={500} aria-label={`联系方式${i+1}备注`} onChange={e=>setContacts(old=>old.map((v,n)=>n===i?{...v,note:e.target.value}:v))}/></label></details></div>)}<button type="button" className="button quiet" disabled={contacts.length>=20} onClick={()=>setContacts(old=>[...old,{type:'QQ',value:'',note:''}])}>＋ 添加联系方式</button></fieldset>
  <fieldset><legend>资料链接</legend>{links.map((l,i)=><div className="archive-field-row" key={i}><label><span className="visually-hidden">链接名称</span><input placeholder="链接名称（选填）" value={l.label} maxLength={100} aria-label={`资料链接${i+1}名称`} onChange={e=>setLinks(old=>old.map((v,n)=>n===i?{...v,label:e.target.value}:v))}/></label><div className="link-main"><label><span className="visually-hidden">网址</span><input placeholder="https://" type="url" required maxLength={2000} value={l.url} aria-label={`资料链接${i+1}网址`} onChange={e=>setLinks(old=>old.map((v,n)=>n===i?{...v,url:e.target.value}:v))}/></label><button type="button" className="icon-close" aria-label={`移除资料链接${i+1}`} onClick={()=>setLinks(old=>old.filter((_,n)=>n!==i))}>×</button></div></div>)}<button type="button" className="button quiet" disabled={links.length>=20} onClick={()=>setLinks(old=>[...old,{label:'',url:''}])}>＋ 添加资料链接</button></fieldset>
 </>;
}
export function StateChoices({value,onChange,choices}:{value:string;onChange:(value:string)=>void;choices:readonly string[]}){
 const name=useId();
 return <fieldset className="state-choice-field"><legend>业务状态</legend><div className="state-choices" role="radiogroup" aria-label="业务状态">{choices.map(s=><label className={value===s?'selected':''} key={s}><input type="radio" name={name} value={s} checked={value===s} onChange={()=>onChange(s)}/><span>{s}</span></label>)}</div></fieldset>;
}
