import React,{useRef,useState,type FormEvent,type ReactNode} from 'react';
import {Icon} from './icons';
import type {MaterialInfo,MaterialCapacity} from '../server/materials';
import './materials.css';

export function fileSize(bytes:number){if(bytes<1000)return `${bytes} B`;if(bytes<1_000_000)return `${(bytes/1000).toFixed(1)} KB`;if(bytes<1_000_000_000)return `${(bytes/1_000_000).toFixed(bytes%1_000_000?1:0)} MB`;return `${(bytes/1_000_000_000).toFixed(2)} GB`;}
export function MaterialList({items,capacity,deleted,onDeleted,onFiles,onEdit,onDelete,onRestore,onPurge,onPreview,onCopy,onQuota,locked,loading,error,onRetry,more,onMore,children,focusId}:{items:MaterialInfo[];capacity:MaterialCapacity|null;deleted:boolean;onDeleted:(value:boolean)=>void;onFiles:(files:File[])=>void;onEdit:(file:MaterialInfo)=>void;onDelete:(file:MaterialInfo)=>void;onRestore:(file:MaterialInfo)=>void;onPurge:(file:MaterialInfo)=>void;onPreview:(file:MaterialInfo)=>void;onCopy:(file:MaterialInfo)=>void;onQuota?:()=>void;locked:boolean;loading:boolean;error?:string;onRetry:()=>void;more?:boolean;onMore:()=>void;children?:ReactNode;focusId?:string}){
 const input=useRef<HTMLInputElement>(null),[drag,setDrag]=useState(false);
 return <section className={'material-library '+(drag?'dragging':'')} aria-label="绑定材料" onDragOver={e=>{if(!locked&&e.dataTransfer.types.includes('Files')){e.preventDefault();setDrag(true);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDrag(false);}} onDrop={e=>{if(locked)return;e.preventDefault();setDrag(false);onFiles([...e.dataTransfer.files]);}}>
  <div className="material-toolbar"><div className="material-scopes"><button className={!deleted?'active':''} aria-pressed={!deleted} onClick={()=>onDeleted(false)}>全部材料</button><button className={deleted?'active':''} aria-pressed={deleted} onClick={()=>onDeleted(true)}>回收站</button></div>{!locked&&<><input ref={input} type="file" aria-label="选择绑定材料" multiple hidden onChange={e=>{onFiles([...e.target.files??[]]);e.target.value='';}}/><button className="button primary" onClick={()=>input.current?.click()}><Icon name="plus"/>上传文件</button></>}</div>
  <div className="material-capacity">{capacity&&<><span>{fileSize(capacity.used_bytes)} / {fileSize(capacity.limit_bytes)}{capacity.reserved_bytes>0&&<small> · 上传预留 {fileSize(capacity.reserved_bytes)}</small>}</span><progress aria-label="材料容量使用" value={capacity.used_bytes+capacity.reserved_bytes} max={capacity.limit_bytes}/></>}{onQuota&&!locked&&<button className="text-button" onClick={onQuota}>调整容量</button>}</div>
  {children}{error&&<p className="form-error" role="alert">{error} <button className="text-button" onClick={onRetry}>重新读取</button></p>}
  <div className="material-files">{items.map(file=><article id={'material-'+file.id} key={file.id} className={'material-row '+(focusId===file.id?'focused':'')}><Icon name="file" size={24}/><div className="material-file-content"><div className="material-file-title"><strong>{file.name}</strong>{file.state==='purging'&&<small>正在清除</small>}</div>{file.description&&<p>{file.description}</p>}<div className="material-file-meta"><span>{fileSize(file.byte_size)}</span><span>{file.owner_name}</span><time>{new Date(file.created_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})}</time></div><div className="material-file-actions">{file.state==='ready'&&<>{file.preview_url&&<button onClick={()=>onPreview(file)}>预览</button>}<a href={file.download_url}>下载</a><button onClick={()=>onCopy(file)}>复制引用</button></>}{file.editable&&<details onClick={e=>{if((e.target as HTMLElement).closest('button'))e.currentTarget.open=false;}}><summary>更多</summary><div className="material-menu">{deleted?<><button onClick={()=>onRestore(file)}>恢复材料</button><button className="danger-text" onClick={()=>onPurge(file)}>彻底删除</button></>:<><button onClick={()=>onEdit(file)}>名称与说明</button><button onClick={()=>onDelete(file)}>删除材料</button></>}</div></details>}</div></div></article>)}</div>
  {loading?<p className="stream-status" role="status">正在读取材料…</p>:!error&&!items.length?<div className="material-empty"><Icon name="folder" size={32}/><p>{deleted?'回收站暂无可查看的材料':'还没有绑定材料'}</p>{!deleted&&!locked&&<small>拖入文件，或点击上传 · 单文件最大 100MB</small>}</div>:more&&<button className="button quiet" onClick={onMore}>加载更多材料</button>}
 </section>;
}
export function MaterialEditForm({file,busy,error,onSubmit,onCancel,onReload}:{file:MaterialInfo;busy:boolean;error:string;onSubmit:(name:string,description:string)=>void;onCancel:()=>void;onReload:()=>void}){const[name,setName]=useState(file.name),[description,setDescription]=useState(file.description);return <form className="material-form" onSubmit={e=>{e.preventDefault();onSubmit(name,description);}}><label>文件名称<input required maxLength={240} value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>材料说明<textarea maxLength={1000} rows={3} value={description} disabled={busy} onChange={e=>setDescription(e.target.value)} placeholder="可选，说明这份材料是什么"/></label>{error&&<p className="form-error" role="alert">{error} <button type="button" className="text-button" onClick={onReload}>重新读取材料</button></p>}<div className="modal-actions"><button type="button" className="button quiet" disabled={busy} onClick={onCancel}>取消</button><button className="button primary" disabled={busy}>{busy?'正在保存…':'保存'}</button></div></form>;}
export function MaterialQuotaForm({capacity,busy,error,onSubmit,onCancel,onReload}:{capacity:MaterialCapacity;busy:boolean;error:string;onSubmit:(bytes:number)=>void;onCancel:()=>void;onReload:()=>void}){const[value,setValue]=useState(String(capacity.limit_bytes/1_000_000));return <form className="material-form" onSubmit={(e:FormEvent)=>{e.preventDefault();onSubmit(Math.round(Number(value)*1_000_000));}}><label>总容量（MB）<input type="number" min={Math.ceil(Math.max(capacity.default_bytes,capacity.used_bytes+capacity.reserved_bytes)/1_000_000)} max={1_000_000} step={1} value={value} onChange={e=>setValue(e.target.value)} required disabled={busy}/></label><p>已用 {fileSize(capacity.used_bytes)}{capacity.reserved_bytes?`，上传预留 ${fileSize(capacity.reserved_bytes)}`:''}</p>{error&&<p className="form-error" role="alert">{error} <button type="button" className="text-button" onClick={onReload}>重新读取容量</button></p>}<div className="modal-actions"><button type="button" className="button quiet" disabled={busy} onClick={onCancel}>取消</button><button className="button primary" disabled={busy}>{busy?'正在保存…':'保存容量'}</button></div></form>;}
