import {spawn} from 'node:child_process';
import {readFileSync,existsSync} from 'node:fs';
import {homedir} from 'node:os';
import {join} from 'node:path';
import {setDefaultResultOrder} from 'node:dns';
import {setDefaultAutoSelectFamily} from 'node:net';
setDefaultResultOrder('ipv4first');setDefaultAutoSelectFamily(false);

// Never forward Wrangler's raw output: SQL exports contain temporary download credentials.
export async function wrangler(args){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,['node_modules/wrangler/bin/wrangler.js',...args],{env:{...process.env,WRANGLER_SEND_METRICS:'false'},stdio:['ignore','pipe','pipe'],windowsHide:true});let output='',error='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>error+=b);child.on('error',()=>reject(new Error('Unable to start the installed Wrangler CLI')));child.on('exit',code=>{if(code===0)resolve(output);else reject(new Error(`Wrangler ${args.slice(0,2).join(' ')} failed (exit ${code}); command output withheld because it may contain private data`));});});}
export function jsonOutput(output){try{return JSON.parse(output);}catch{const first=output.indexOf('[');if(first>=0)return JSON.parse(output.slice(first));throw new Error('Wrangler returned an unexpected JSON response');}}
export function projectConfig(){const config=JSON.parse(readFileSync('wrangler.jsonc','utf8')),release=JSON.parse(readFileSync('release.config.json','utf8'));return {config,release};}
let cachedToken;
export async function cloudflareToken(){if(process.env.CLOUDFLARE_API_TOKEN)return process.env.CLOUDFLARE_API_TOKEN;if(process.env.CI)throw new Error('CI requires its own scoped CLOUDFLARE_API_TOKEN');if(cachedToken)return cachedToken;const paths=[process.env.CTS_WRANGLER_AUTH_FILE,process.env.APPDATA&&join(process.env.APPDATA,'xdg.config','.wrangler','config','default.toml'),join(homedir(),'.config','.wrangler','config','default.toml')].filter(Boolean),path=paths.find(existsSync);if(!path)throw new Error('Wrangler authentication file not found; use the documented API token environment variable');let raw=readFileSync(path,'utf8');const expiration=raw.match(/^expiration_time\s*=\s*"([^"]+)"/m);if(expiration&&Date.parse(expiration[1])<Date.now()+60000){await wrangler(['whoami']);raw=readFileSync(path,'utf8');}const match=raw.match(/^(?:oauth_token|api_token)\s*=\s*"([^"]+)"/m);if(!match)throw new Error('No reusable Wrangler management credential found');return cachedToken=match[1];}
export async function cf(path,{method='GET',body,headers={},raw=false,allowMissing=false}={}){const token=await cloudflareToken();let response;const attempts=['GET','PUT'].includes(method)?3:1;
 for(let attempt=0;attempt<attempts;attempt++){try{response=await fetch('https://api.cloudflare.com/client/v4'+path,{method,headers:{Authorization:'Bearer '+token,...headers},...(body!==undefined?{body}:{}),signal:AbortSignal.timeout(45000)});if(response.status>=500&&attempt<attempts-1){await response.arrayBuffer();continue;}break;}catch{if(attempt===attempts-1)throw new Error(`Cloudflare ${method} transport failed; no response details logged`);}}
 if(response.status===404&&allowMissing)return null;if(!response.ok)throw new Error(`Cloudflare ${method} rejected (${response.status}); private response omitted`);if(raw)return response;const data=await response.json();if(data.success===false)throw new Error(`Cloudflare ${method} reported failure (${data.errors?.map(e=>e.code).join(',')??'unknown'})`);return data.result;
}
export function objectPath(account,bucket,key){return `/accounts/${account}/r2/buckets/${encodeURIComponent(bucket)}/objects/${key.split('/').map(encodeURIComponent).join('/')}`;}
export async function d1Query(databaseId,sql,params=[]){const {config}=projectConfig();const result=await cf(`/accounts/${config.account_id}/d1/database/${databaseId}/query`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sql,params})});if(!Array.isArray(result)||result.some(r=>!r.success))throw new Error('D1 management query failed');return result;}
export async function d1Batch(databaseId,batch){const {config}=projectConfig();const result=await cf(`/accounts/${config.account_id}/d1/database/${databaseId}/query`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({batch})});if(!Array.isArray(result)||result.some(r=>!r.success))throw new Error('D1 management batch failed');return result;}
export function managementDatabase(databaseId){const wrap=(sql,params=[])=>({sql,params,bind(...values){return wrap(sql,values);},async first(column){const result=(await d1Query(databaseId,sql,params))[0].results?.[0]??null;return result&&column?result[column]:result;},async all(){return (await d1Query(databaseId,sql,params))[0];},async run(){return (await d1Query(databaseId,sql,params))[0];}});return {prepare:sql=>wrap(sql),batch:statements=>d1Batch(databaseId,statements.map(({sql,params})=>({sql,params})))};}
