import {createHash,randomUUID} from 'node:crypto';
import {mkdtempSync,readFileSync,writeFileSync,rmSync,statSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {gzipSync} from 'node:zlib';
import {DatabaseSync} from 'node:sqlite';
import {fileURLToPath} from 'node:url';
import {cf,objectPath,projectConfig,wrangler} from './lib/cloudflare-admin.mjs';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
export async function backup(environment,{existingExport}={}){
 const {config,release}=projectConfig(),target=config.env[environment];if(!release.environments[environment]||!target)throw new Error('Unknown backup environment');const db=target.d1_databases[0],bucket=target.r2_buckets.find(b=>b.binding==='IMAGES').bucket_name,account=config.account_id,folder=mkdtempSync(join(tmpdir(),'cts-backup-')),started=new Date().toISOString(),snapshot=`snapshots/${environment}/${started.replaceAll(':','-')}-${randomUUID()}`,exportFile=existingExport?resolve(existingExport):join(folder,'database.sql');
 try{
  if(!existingExport)await wrangler(['d1','export',db.database_name,'--env',environment,'--remote','--output',exportFile]);if(statSync(exportFile).size>release.max_export_bytes)throw new Error('SQL export exceeds the reviewed backup memory bound');const sql=readFileSync(exportFile),sqlite=new DatabaseSync(':memory:');let objects,migrations,counts;
  try{sqlite.exec(sql.toString('utf8'));objects=sqlite.prepare("SELECT object_key,sha256,byte_size FROM attachments WHERE state='ready' AND (EXISTS(SELECT 1 FROM version_attachments v WHERE v.attachment_id=attachments.id) OR EXISTS(SELECT 1 FROM draft_attachments d WHERE d.attachment_id=attachments.id) OR EXISTS(SELECT 1 FROM avatar_history h WHERE h.attachment_id=attachments.id OR h.previous_attachment_id=attachments.id) OR EXISTS(SELECT 1 FROM archives a WHERE a.avatar_id=attachments.id) OR EXISTS(SELECT 1 FROM members m WHERE m.avatar_id=attachments.id)) ORDER BY object_key").all();migrations=sqlite.prepare('SELECT name FROM d1_migrations ORDER BY id').all().map(r=>r.name);counts=Object.fromEntries(['members','archives','observations','observation_versions','version_attachments','tags','tag_categories','archive_tags','tag_definition_history','archive_events','mcp_tasks','mcp_calls'].map(table=>[table,sqlite.prepare(`SELECT count(*) n FROM ${table}`).get().n]));}finally{sqlite.close();}
  const inventory=new Map();let uploaded=0,bytes=0;
  for(const object of objects){const key=`images/${object.sha256}`,path=objectPath(account,release.backup_bucket,key);if(!inventory.has(object.sha256)){const existing=await cf(path,{raw:true,allowMissing:true});if(!existing){const response=await cf(objectPath(account,bucket,object.object_key),{raw:true}),data=Buffer.from(await response.arrayBuffer());if(data.length!==object.byte_size||hash(data)!==object.sha256)throw new Error('Referenced image failed backup integrity verification');await cf(path,{method:'PUT',body:data,headers:{'Content-Type':'application/octet-stream'},raw:true});uploaded++;bytes+=data.length;}else{const prior=Buffer.from(await existing.arrayBuffer());if(prior.length!==object.byte_size||hash(prior)!==object.sha256)throw new Error('Stored backup image does not match its content address');}inventory.set(object.sha256,key);}object.backup_key=key;}
  const compressed=gzipSync(sql),manifest={format:1,environment,created_at:started,database_id:db.database_id,source_bucket:bucket,sql_key:snapshot+'/database.sql.gz',sql_sha256:hash(sql),compressed_sha256:hash(compressed),sql_bytes:sql.length,migrations,counts,objects};
  await cf(objectPath(account,release.backup_bucket,manifest.sql_key),{method:'PUT',body:compressed,headers:{'Content-Type':'application/gzip'},raw:true});
  // Manifest is the commit marker and is written only after every object is durable.
  await cf(objectPath(account,release.backup_bucket,snapshot+'/manifest.json'),{method:'PUT',body:JSON.stringify(manifest),headers:{'Content-Type':'application/json'},raw:true});
  console.log(JSON.stringify({backup:'complete',environment,snapshot,referenced_images:objects.length,new_image_blobs:uploaded,new_image_bytes:bytes,sql_bytes:sql.length}));return {snapshot,manifest};
 }finally{if(!folder.startsWith(join(tmpdir(),'cts-backup-')))throw new Error('Unexpected backup working directory');rmSync(folder,{recursive:true,force:true});}
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const args=process.argv.slice(2),environment=args[args.indexOf('--env')+1];if(!args.includes('--env'))throw new Error('Use --env staging|production');const r=await backup(environment,{existingExport:args.includes('--existing-export')?args[args.indexOf('--existing-export')+1]:undefined});if(process.env.GITHUB_OUTPUT)writeFileSync(process.env.GITHUB_OUTPUT,`snapshot=${r.snapshot}\n`,{flag:'a'});}
