import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,writeFileSync,rmSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {gunzipSync} from 'node:zlib';
import {snapshotDatabase} from './lib/snapshot-database.mjs';
import {fileURLToPath} from 'node:url';
import {cf,d1Query,objectPath,projectConfig,wrangler,managementDatabase} from './lib/cloudflare-admin.mjs';
import {cleanupJournal} from '../app/server/mcp-journal.ts';
const hash=data=>createHash('sha256').update(data).digest('hex');
export function validateRecoveryTarget(config,release){const r=release.recovery;if(!r?.database_name.startsWith('cts-restore-')||!r.bucket_name.startsWith('cts-restore-'))throw new Error('Recovery requires the explicitly configured isolated target');for(const env of Object.values(config.env)){if(env.d1_databases?.some(db=>db.database_id===r.database_id||db.database_name===r.database_name)||env.r2_buckets?.some(b=>b.bucket_name===r.bucket_name))throw new Error('Recovery target overlaps a live environment');}if(r.bucket_name===release.backup_bucket)throw new Error('Recovery cannot overwrite the backup bucket');return r;}
export async function restore(snapshot){const {config,release}=projectConfig(),target=validateRecoveryTarget(config,release);if(!/^snapshots\/(production|staging)\/[a-zA-Z0-9T.:-]+$/.test(snapshot))throw new Error('Invalid snapshot path');const account=config.account_id,folder=mkdtempSync(join(tmpdir(),'cts-restore-'));
 try{
  const manifestResponse=await cf(objectPath(account,release.backup_bucket,snapshot+'/manifest.json'),{raw:true}),manifest=await manifestResponse.json();assert.equal(manifest.format,1);assert.equal(manifest.sql_key,snapshot+'/database.sql.gz');
  const packed=Buffer.from(await (await cf(objectPath(account,release.backup_bucket,manifest.sql_key),{raw:true})).arrayBuffer());assert.equal(hash(packed),manifest.compressed_sha256);const sql=gunzipSync(packed,{maxOutputLength:release.max_export_bytes});assert.equal(hash(sql),manifest.sql_sha256);assert.equal(sql.length,manifest.sql_bytes);
  const existing=(await d1Query(target.database_id,"SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE '_cf_%' AND name NOT LIKE 'sqlite_%'"))[0].results;assert.equal(existing.length,0,'Recovery only imports into an empty isolated database; never clears a live or partial target');
  const file=join(folder,'restore.sql'),configFile=join(folder,'wrangler.json');writeFileSync(file,sql,{mode:0o600});writeFileSync(configFile,JSON.stringify({name:'cts-recovery-management',account_id:account,d1_databases:[{binding:'DB',database_name:target.database_name,database_id:target.database_id}]}));
  await wrangler(['d1','execute',target.database_name,'--config',configFile,'--remote','--file',file,'--json']);
  const sqlite=snapshotDatabase(sql);let tableHashes={};try{for(const row of sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE '_cf_%' AND name NOT LIKE 'sqlite_%' ORDER BY name").all()){assert.match(row.name,/^[a-zA-Z0-9_]+$/);const source=sqlite.prepare(`SELECT * FROM ${row.name}`).all(),restored=(await d1Query(target.database_id,`SELECT * FROM ${row.name}`))[0].results;const canonical=rows=>rows.map(r=>JSON.stringify(Object.fromEntries(Object.entries(r).sort(([a],[b])=>a.localeCompare(b))))).sort().join('\n');assert.equal(hash(canonical(restored)),hash(canonical(source)),`Restored table ${row.name} differs from the snapshot`);tableHashes[row.name]={rows:source.length,sha256:hash(canonical(source))};}}finally{sqlite.close();}
  let images=0;for(const object of manifest.objects){assert.match(object.sha256,/^[a-f0-9]{64}$/);assert.equal(object.backup_key,'images/'+object.sha256);const bytes=Buffer.from(await (await cf(objectPath(account,release.backup_bucket,object.backup_key),{raw:true})).arrayBuffer());assert.equal(hash(bytes),object.sha256);assert.equal(bytes.length,object.byte_size);await cf(objectPath(account,target.bucket_name,object.object_key),{method:'PUT',body:bytes,raw:true});const restored=Buffer.from(await (await cf(objectPath(account,target.bucket_name,object.object_key),{raw:true})).arrayBuffer());assert.equal(hash(restored),object.sha256);images++;}
  // Apply the same application retention policy before any restored service could be exposed.
  await cleanupJournal({DB:managementDatabase(target.database_id)});await cleanupJournal({DB:managementDatabase(target.database_id)});
  const counts=(await d1Query(target.database_id,'SELECT (SELECT count(*) FROM observations) observations,(SELECT count(*) FROM observation_versions) versions,(SELECT count(*) FROM version_attachments) image_references'))[0].results[0];assert.equal(counts.observations,manifest.counts.observations);assert.equal(counts.versions,manifest.counts.observation_versions);assert.equal(counts.image_references,manifest.counts.version_attachments);
  const report={date:new Date().toISOString(),snapshot,target:{database_id:target.database_id,bucket_name:target.bucket_name},tables:tableHashes,images_verified:images,cleanup:'application cleanup executed twice; business observations, versions and attachment references unchanged',public_worker_created:false};mkdirSync('tmp/verification',{recursive:true});writeFileSync('tmp/verification/recovery.json',JSON.stringify(report,null,2));console.log(JSON.stringify({restore:'complete',tables:Object.keys(tableHashes).length,images,cleanup:'pass',public_worker_created:false}));return report;
 }finally{if(!folder.startsWith(join(tmpdir(),'cts-restore-')))throw new Error('Unexpected recovery working directory');rmSync(folder,{recursive:true,force:true});}
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const args=process.argv.slice(2);if(!args.includes('--snapshot'))throw new Error('Use --snapshot snapshots/<environment>/<id>');await restore(args[args.indexOf('--snapshot')+1]);}
