import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {verificationClient} from './verification-client.mjs';
const v=await verificationClient('images'),checks=[],members=[],ids={};let extra,hidden;
const fixture=ext=>readFileSync(new URL('../tests/fixtures/images/shapes.'+ext,import.meta.url));
const png=fixture('png'),jpeg=fixture('jpg'),webp=fixture('webp');
async function sql(text){const file=`tmp/verification/images-fixture-${v.target}.sql`;writeFileSync(file,text);const env={...process.env,NODE_OPTIONS:'--dns-result-order=ipv4first --no-network-family-autoselection'};for(const name of ['HTTP_PROXY','HTTPS_PROXY','ALL_PROXY'])delete env[name];const r=spawnSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','d1','execute','cts-staging','--env','staging',v.target==='cloud'?'--remote':'--local','--command',text,'--json'],{encoding:'utf8',env});assert.equal(r.status,0,'synthetic image fixture SQL: '+r.stderr+' '+r.stdout.slice(-1800));return JSON.parse(r.stdout.slice(r.stdout.search(/^\s*\[/m)))[0].results;}
async function post(path,body){const r=await v.http(path,body);assert.equal(r.status,200,JSON.stringify(r.body));return r.body;}
async function rejected(tool,args,code){const r=await v.client.callTool({name:tool,arguments:args});assert.equal(r.isError,true,tool+' should reject');assert.equal(r.structuredContent.error.code,code);}
const metadata=(bytes,mime='image/png')=>({mime_type:mime,byte_size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});
async function prepare(archive,bytes=png,mime='image/png',purpose='observation'){return v.call('prepare_image_upload',{purpose,archive_id:archive,...metadata(bytes,mime)});}
async function put(ticket,bytes=png,headers={}){const r=await fetch(ticket.url,{method:'PUT',headers:{...ticket.headers,...headers,Connection:'close'},body:bytes});const text=await r.text();assert.ok(r.headers.get('Content-Type')?.includes('json'),`upload route ${ticket.url} status ${r.status}: ${text.slice(0,100)}`);return {status:r.status,body:JSON.parse(text)};}
async function uploaded(archive,bytes=png,mime='image/png',purpose='observation'){const ticket=await prepare(archive,bytes,mime,purpose),r=await put(ticket,bytes);assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.state,'ready');return {ticket,image:r.body.attachment};}
async function imageStatus(id,token){const r=await fetch(v.base+'/images/'+id,{headers:{...(token?{Authorization:'Bearer '+token}:{}),Connection:'close'}});const bytes=await r.arrayBuffer();return {status:r.status,headers:r.headers,bytes:Buffer.from(bytes)};}
async function avatar(type,id,token){const r=await fetch(v.base+`/avatars/${type}/${id}`,{headers:{Authorization:'Bearer '+token,Connection:'close'}});return {status:r.status,mime:r.headers.get('Content-Type'),bytes:Buffer.from(await r.arrayBuffer())};}
try{
 const suffix=randomUUID().slice(0,8),archive=await v.call('create_archive',{type:'person',name:'虚构图文验收 '+suffix,request_id:randomUUID()}),other=await v.call('create_archive',{type:'org',name:'虚构图片隔离 '+suffix,request_id:randomUUID()});ids.archive=archive.id;ids.other=other.id;
 extra=await post('/connections',{name:'图片读取验收 '+suffix,days:1});
 const bad=await prepare(archive.id);assert.equal((await put(bad,png,{'X-Upload-Ticket':'ctsu_'+'f'.repeat(64)})).status,401);assert.equal((await put(bad,png,{'Content-Type':'image/jpeg'})).body.error.code,'UPLOAD_METADATA_MISMATCH');
 const changed=Buffer.from(png);changed[100]^=1;assert.equal((await put(bad,changed)).body.error.code,'IMAGE_CONTENT_MISMATCH');assert.equal((await v.call('get_upload_status',{upload_id:bad.upload_id})).state,'pending');assert.equal((await put(bad)).status,200);assert.equal((await put(bad)).body.error.code,'UPLOAD_ALREADY_COMPLETE');
 const expired=await prepare(archive.id);await sql(`UPDATE attachments SET ticket_expires_at='2020-01-01T00:00:00.000Z' WHERE id='${expired.upload_id}';`);assert.equal((await put(expired)).status,410);
 assert.equal((await v.http('/images/prepare',{purpose:'observation',archive_id:archive.id,...metadata(png),byte_size:10485761})).status,400);
 const fakeBytes=Buffer.from('<svg><script>bad</script></svg>'),fake=await prepare(archive.id,fakeBytes);assert.equal((await put(fake,fakeBytes)).body.error.code,'INVALID_IMAGE');
 const wrongFormat=await prepare(archive.id,jpeg);assert.equal((await put(wrongFormat,jpeg)).body.error.code,'IMAGE_CONTENT_MISMATCH');
 checks.push('upload tickets enforce secret, MIME, length, SHA-256, expiry, single completion and supported actual container; rejected transfer can retry immutable bytes');
 const images=[{id:bad.attachment_id},(await uploaded(archive.id,jpeg,'image/jpeg')).image,(await uploaded(archive.id,webp,'image/webp')).image];ids.images=images.map(i=>i.id);
 const initial={archive_id:archive.id,body:'虚构图文记录：红色方形、蓝色圆形。',attachment_ids:ids.images,request_id:randomUUID()};
 await rejected('create_observation',{...initial,archive_id:other.id},'ATTACHMENT_UNAVAILABLE');
 assert.equal((await v.http('/observations/create',{...initial,attachment_ids:Array(11).fill(images[0].id)})).status,400);
 const record=await v.call('create_observation',initial);ids.observation=record.id;assert.equal((await v.call('create_observation',initial)).replayed,true);
 const current=(await v.call('get_observation',{id:record.id})).observation;assert.deepEqual(current.attachments.map(i=>i.id),ids.images);assert.ok(current.attachments.every(i=>i.width===240&&i.height===160&&i.url.startsWith(v.base+'/images/')));
 const viewed=await v.client.callTool({name:'get_image',arguments:{attachment_id:images[0].id}});assert.ok(!viewed.isError);assert.equal(viewed.content[0].type,'image');assert.equal(viewed.content[0].mimeType,'image/png');assert.deepEqual(Buffer.from(viewed.content[0].data,'base64'),png);assert.ok(!JSON.stringify(viewed.structuredContent).includes('base64'));
 assert.deepEqual((await v.http('/observations/'+record.id)).body.observation.attachments.map(i=>i.id),ids.images);
 const removed=await v.call('update_observation',{id:record.id,expected_version:1,body:initial.body,occurred_at:null,attachment_ids:[images[1].id],request_id:randomUUID()});assert.equal(removed.content_version,2);
 assert.equal((await v.call('update_observation',{id:record.id,expected_version:2,body:initial.body,occurred_at:null,request_id:randomUUID()})).changed,false);
 const history=await v.call('list_observation_versions',{id:record.id});assert.deepEqual(history.versions[1].attachments.map(i=>i.id),ids.images);assert.equal(history.versions[0].attachments.length,1);
 const firstImage=await imageStatus(images[0].id,extra.secret);assert.equal(firstImage.status,200);assert.deepEqual(firstImage.bytes,png);assert.equal(firstImage.headers.get('Cache-Control'),'private, no-store');assert.equal(firstImage.headers.get('X-Content-Type-Options'),'nosniff');assert.equal((await imageStatus(images[0].id)).status,401);
 checks.push('MCP returns standard image content; HTTP metadata agrees; ordered attachments, current edits and immutable history survive idempotent retries and old image reads');
 const draftImage=(await uploaded(archive.id)).image;
 const saved=await post('/drafts/save',{archive_id:archive.id,expected_version:0,body:'',occurred_at:null,attachment_ids:[draftImage.id],request_id:randomUUID()});assert.equal((await v.http('/drafts')).body.drafts.some(d=>d.archive_id===archive.id),true);const draft=(await v.http('/drafts/'+archive.id)).body.draft;assert.equal(draft.attachments[0].id,draftImage.id);
 const textOnlyOldClient=await post('/drafts/save',{archive_id:archive.id,expected_version:saved.version,body:'',occurred_at:null,request_id:randomUUID()});assert.equal(textOnlyOldClient.changed,false);
 const imageOnly=await v.call('create_observation',{archive_id:archive.id,attachment_ids:[draftImage.id],request_id:draft.publish_request_id});assert.equal((await v.call('get_observation',{id:imageOnly.id})).observation.body,'');assert.equal((await v.http('/drafts/'+archive.id)).body.published.id,imageOnly.id);
 await post('/drafts/save',{archive_id:archive.id,expected_version:saved.version,body:'',occurred_at:null,attachment_ids:[],request_id:randomUUID()});assert.equal((await v.http('/drafts')).body.drafts.some(d=>d.archive_id===archive.id),false);
 checks.push('image-only drafts are discoverable, reload with attachments, support older text-only clients and publish once using their durable request ID');
 const name='images-'+suffix,temp='ImageTemp!'+randomUUID(),password='ImageMember!'+randomUUID(),member=await v.call('create_member',{username:name,name:'虚构图片读者',temporary_password:temp,request_id:randomUUID()});members.push(member.id);let cookie;
 async function memberHttp(path,body){const r=await fetch(v.base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:v.base,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),Connection:'close'},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,body:await r.json()};}
 assert.equal((await memberHttp('/auth/login',{username:name,password:temp})).status,200);assert.equal((await memberHttp('/auth/password',{current_password:temp,new_password:password})).status,200);assert.equal((await memberHttp('/auth/login',{username:name,password})).status,200);const connection=(await memberHttp('/connections',{name:'图片权限验收',days:1})).body;
 assert.equal((await imageStatus(images[0].id,connection.secret)).status,200);const unbound=await uploaded(archive.id);assert.equal((await imageStatus(unbound.image.id,connection.secret)).status,404);assert.equal((await memberHttp('/images/uploads/'+unbound.image.id)).status,404);
 assert.equal((await memberHttp('/observations/create',{archive_id:archive.id,attachment_ids:[unbound.image.id],request_id:randomUUID()})).status,400);
 hidden=record.id;await sql(`UPDATE observations SET deleted=1,deleted_at='2026-09-08T00:00:00.000Z' WHERE id='${record.id}';`);assert.equal((await imageStatus(images[0].id,connection.secret)).status,404);assert.equal((await imageStatus(images[0].id,extra.secret)).status,200);assert.equal((await memberHttp('/observations/'+record.id+'/versions')).status,404);await sql(`UPDATE observations SET deleted=0,deleted_at=NULL WHERE id='${record.id}';`);hidden=null;assert.equal((await imageStatus(images[0].id,connection.secret)).status,200);
 checks.push('unbound images are owner-only; another member can read shared history until current deletion removes access, and restoration makes the same old image readable');
 const personAvatar=await uploaded(archive.id,png,'image/png','archive_avatar'),orgAvatar=await uploaded(other.id,webp,'image/webp','archive_avatar');let a=(await v.call('get_archive',{id:archive.id})).archive;
 const set=await v.call('set_avatar',{subject_type:'archive',id:archive.id,expected_version:a.version,attachment_id:personAvatar.image.id,request_id:randomUUID()});assert.equal(set.version,a.version+1);assert.deepEqual((await avatar('archives',archive.id,connection.secret)).bytes,png);
 await rejected('set_avatar',{subject_type:'archive',id:other.id,expected_version:1,attachment_id:personAvatar.image.id,request_id:randomUUID()},'ATTACHMENT_UNAVAILABLE');
 await v.call('set_avatar',{subject_type:'archive',id:other.id,expected_version:1,attachment_id:orgAvatar.image.id,request_id:randomUUID()});assert.equal((await avatar('archives',other.id,extra.secret)).mime,'image/webp');
 const own=(await memberHttp('/auth/me')).body.member;assert.equal((await memberHttp('/profile',{id:own.id,expected_version:own.version,name:own.name,qq:'00000',request_id:randomUUID()})).status,200);
 assert.equal((await memberHttp('/profile',{id:v.actor.id,expected_version:v.actor.version,name:'不应修改',qq:null,request_id:randomUUID()})).status,403);
 const memberTicket=(await memberHttp('/images/prepare',{purpose:'member_avatar',member_id:member.id,...metadata(jpeg,'image/jpeg')})).body;assert.equal((await put(memberTicket,jpeg)).status,200);
 const ownNow=(await memberHttp('/auth/me')).body.member;assert.equal((await memberHttp('/avatars/set',{subject_type:'member',id:ownNow.id,expected_version:ownNow.version,attachment_id:memberTicket.attachment_id,request_id:randomUUID()})).status,200);assert.deepEqual((await avatar('members',member.id,extra.secret)).bytes,jpeg);
 // Seed only reserved invalid QQ cache with our private synthetic object: no real person's photo is fetched.
 const object=(await sql(`SELECT object_key FROM attachments WHERE id='${personAvatar.image.id}';`))[0].object_key;
 await sql(`INSERT INTO qq_avatar_cache(qq,object_key,mime_type,refreshed_at,refresh_after) VALUES('00000','${object}','image/png','2026-09-08T00:00:00.000Z','2099-01-01T00:00:00.000Z') ON CONFLICT(qq) DO UPDATE SET object_key=excluded.object_key,mime_type=excluded.mime_type,refresh_after=excluded.refresh_after;`);
 assert.deepEqual((await avatar('members',member.id,extra.secret)).bytes,jpeg,'uploaded avatar remains ahead of QQ cache');const ownLast=(await memberHttp('/auth/me')).body.member;assert.equal((await memberHttp('/avatars/set',{subject_type:'member',id:member.id,expected_version:ownLast.version,attachment_id:null,request_id:randomUUID()})).status,200);assert.deepEqual((await avatar('members',member.id,extra.secret)).bytes,png,'removing upload returns cached QQ');assert.equal((await memberHttp('/auth/me')).body.member.qq,'00000');
 a=(await v.call('get_archive',{id:other.id})).archive;await v.call('update_archive',{id:other.id,expected_version:a.version,name:a.name,contacts:[{type:'QQ',value:'00000'}],links:[],request_id:randomUUID()});a=(await v.call('get_archive',{id:other.id})).archive;await v.call('set_avatar',{subject_type:'archive',id:other.id,expected_version:a.version,attachment_id:null,request_id:randomUUID()});assert.equal((await avatar('archives',other.id,extra.secret)).status,404,'organization never falls back to QQ');
 checks.push('avatars bind to their declared subject, share authenticated reads, advance profile history, prefer uploaded bytes over QQ and preserve QQ when removed; organizations skip QQ');
 const revokedTicket=(await memberHttp('/images/prepare',{purpose:'observation',archive_id:archive.id,...metadata(png)})).body;
 const m=(await v.call('get_member',{id:member.id})).member;await v.call('set_member_frozen',{id:member.id,expected_version:m.version,frozen:true,request_id:randomUUID()});assert.equal((await put(revokedTicket)).body.error.code,'UPLOAD_AUTH_EXPIRED');assert.equal((await imageStatus(images[0].id,connection.secret)).status,401);assert.equal((await avatar('archives',archive.id,connection.secret)).status,401);
 const frozen=(await v.call('get_member',{id:member.id})).member;await v.call('set_member_frozen',{id:member.id,expected_version:frozen.version,frozen:false,request_id:randomUUID()});assert.equal((await put(revokedTicket)).status,401);assert.equal((await imageStatus(images[0].id,connection.secret)).status,401);
 const closureTicket=await prepare(other.id);a=(await v.call('get_archive',{id:other.id})).archive;await v.call('set_archive_state',{id:other.id,expected_version:a.version,status:'已弃用',member_ids:[],request_id:randomUUID()});assert.equal((await put(closureTicket)).body.error.code,'ARCHIVE_CLOSED');await rejected('prepare_image_upload',{purpose:'archive_avatar',archive_id:other.id,...metadata(png)},'ARCHIVE_CLOSED');a=(await v.call('get_archive',{id:other.id})).archive;await rejected('set_avatar',{subject_type:'archive',id:other.id,expected_version:a.version,attachment_id:orgAvatar.image.id,request_id:randomUUID()},'ARCHIVE_CLOSED');assert.equal((await imageStatus(orgAvatar.image.id,extra.secret)).status,200);
 checks.push('freeze and epoch invalidation immediately reject image reads and original upload tickets; unfreezing does not revive them; closed archives reject upload/avatar mutations but retain history');
 const calls=(await v.http('/admin/calls?limit=100')).body.calls;for(const tool of ['prepare_image_upload','get_image']){const call=calls.find(c=>c.tool===tool);if(call){const detail=(await v.http('/admin/calls/'+call.id)).body;assert.ok(!JSON.stringify(detail).includes('ctsu_'));assert.ok(!JSON.stringify(detail).includes('iVBOR'));}}
 checks.push('request journal records metadata for upload and image tools without tickets or binary payloads');
 writeFileSync(`tmp/verification/image-artifacts-${v.target}.json`,JSON.stringify({date:new Date().toISOString(),base:v.base,...ids},null,2));
}finally{
 if(hidden)await sql(`UPDATE observations SET deleted=0,deleted_at=NULL WHERE id='${hidden}';`);
 for(const id of members){const m=(await v.call('get_member',{id})).member;if(!m.frozen)await v.call('set_member_frozen',{id,expected_version:m.version,frozen:true,request_id:randomUUID()});}
 if(extra)await v.http('/connections/revoke',{id:extra.id});await v.close(checks);
}
