import React, { useState, useRef, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { Icon, Mark } from './icons.jsx';
import { IdentityArt } from './IdentityArt.jsx';
import { ContactFields } from './ContactFields.jsx';
import { initialEntities, initialMembers, personStates, orgStates, isClosed, uuid, stamp, timelineOrder } from './model.js';
import './style.css';
import './refinement.css';

const currentUser='zhou';
const navItems=[['person','people','人物'],['org','org','组织'],['unread','bell','未读更新']];
const names={person:'人物',org:'组织',unread:'未读更新',accounts:'账号管理',agent:'Agent 接入'};
const ownerLabel=s=>s==='人事审核'?'审核负责人':s==='已加入待对接'?'对接负责人':'接触负责人';
const ownerStates=type=>type==='org'?['个人接触','组织交流']:['个人接触','引荐中（待人事组接触）','人事审核','已加入待对接'];
function Button({children,icon,variant='',className='',...props}) {return <button className={`button ${variant} ${className}`} {...props}>{icon&&<Icon name={icon}/>}<span>{children}</span></button>;}
function IconButton({name,label,...props}) {return <button className="icon-button" title={label} aria-label={label} {...props}><Icon name={name}/></button>;}
function StateTag({state}) {return <span className={`state-tag ${isClosed(state)?'closed':['个人接触','组织交流'].includes(state)?'contact':''}`}><i/>{state}</span>;}
function Empty({title,children,action}) {return <div className="empty"><span className="empty-mark"><i/><i/><i/></span><h3>{title}</h3><p>{children}</p>{action}</div>;}
function Modal({title,children,onClose,wide=false}) {
 const ref=useRef(null);
 useEffect(()=>{ref.current?.showModal();},[]);
 return <dialog ref={ref} className={`modal ${wide?'wide':''}`} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-head"><h2>{title}</h2><IconButton name="close" label="关闭对话框" onClick={onClose}/></div>{children}</dialog>;
}
function App(){
 const [entities,setEntities]=useState(initialEntities);
 const [members,setMembers]=useState(initialMembers);
 const [page,setPage]=useState('person');
 const [selected,setSelected]=useState('p1');
 const [search,setSearch]=useState('');
 const [stateFilter,setStateFilter]=useState('all');
 const [lifeFilter,setLifeFilter]=useState('open');
 const [ownerFilter,setOwnerFilter]=useState('all');
 const [recordView,setRecordView]=useState('all');
 const [text,setText]=useState('');
 const [images,setImages]=useState([]);
 const [composeOpen,setComposeOpen]=useState(false);
 const [dialog,setDialog]=useState(null);
 const [toast,setToast]=useState('');
 const [loggedIn,setLoggedIn]=useState(new URLSearchParams(location.search).get('page')!=='login');
 const [mobileNav,setMobileNav]=useState(false);
 const [detailWide,setDetailWide]=useState(false);
 const inputFile=useRef(null);
 const composerText=useRef(null);
 const entity=entities.find(e=>e.id===selected);
 const actor=members.find(m=>m.id===currentUser);
 const memberName=id=>members.find(m=>m.id===id)?.name??id;
 const notify=message=>setToast(message);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{const listener=e=>{if(e.key==='Escape'&&!dialog){setSelected(null);setMobileNav(false);}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[dialog]);
 function navigate(next){setPage(next);setSelected(null);setSearch('');setStateFilter('all');setLifeFilter('open');setOwnerFilter('all');setMobileNav(false);setRecordView('all');setText('');setImages([]);setComposeOpen(false);setDetailWide(false);}
 function pick(id){setSelected(id);setRecordView('all');setText('');setImages([]);setComposeOpen(false);setDetailWide(false);}
 function mutate(id,change,message){setEntities(prev=>{const target=prev.find(e=>e.id===id);const result={...change(structuredClone(target)),updated:'刚刚'};return [result,...prev.filter(e=>e.id!==id)];});if(message)notify(message);}
 function addEvent(target,message){target.events.unshift({id:uuid(),kind:'system',order:Date.now(),actor:currentUser,time:stamp(),text:message});return target;}
 function changeState(next){if(next===entity.state)return;mutate(entity.id,d=>{const old=d.state;if(!isClosed(old)&&isClosed(next))d.lastOpenState=old;d.state=next;return addEvent(d,`将业务状态从「${old}」改为「${next}」${isClosed(next)?'，并关闭档案':isClosed(old)?'，并重新开启档案':''}`);},isClosed(next)?'档案已关闭':'状态已更新');}
 function publish(){if(!entity||isClosed(entity.state)||(!text.trim()&&!images.length))return;const now=stamp();mutate(entity.id,d=>{d.records.unshift({id:uuid(),author:currentUser,order:Date.now(),time:now,body:text.trim(),images,deleted:false,versions:[{body:text.trim(),images,time:now,actor:currentUser,operation:'创建'}]});return d;},'观察记录已发布');setText('');setImages([]);setComposeOpen(false);}
 function recordAction(record,operation,body){if(operation==='编辑'&&record.body===body){setDialog(null);notify('内容没有变化');return;}mutate(entity.id,d=>{const r=d.records.find(x=>x.id===record.id);if(operation==='编辑')r.body=body;if(operation==='删除')r.deleted=true;if(operation==='恢复')r.deleted=false;if(operation==='编辑')r.edited=stamp();r.versions.push({body:r.body,images:r.images,time:stamp(),actor:currentUser,operation});return addEvent(d,`${operation}了一条观察记录`);},`记录已${operation}`);setDialog(null);}
 function readEntity(id){setEntities(prev=>prev.map(e=>e.id===id?{...e,unread:false}:e));notify('已标记为已读');}
 const unread=entities.filter(e=>e.unread);
 const states=page==='org'?orgStates:personStates;
 const filtered=entities.filter(e=>e.type===page&&(!search||`${e.name} ${e.alias} ${e.intro} ${e.records.filter(r=>!r.deleted).map(r=>r.body).join(' ')}`.toLowerCase().includes(search.toLowerCase()))&&(stateFilter==='all'||e.state===stateFilter)&&(lifeFilter==='all'||(lifeFilter==='closed'===isClosed(e.state)))&&(ownerFilter==='all'||Object.values(e.owners).flat().includes(ownerFilter)));
 const detailVisible=!!entity&&['person','org','unread'].includes(page);
 const locked=entity&&isClosed(entity.state);
 const dialogClose=()=>setDialog(null);

 if(!loggedIn)return <div className="login-page"><div className="login-brand"><Mark/><span>康米巨星猎头系统</span></div><div className="login-art" aria-hidden="true"><IdentityArt/></div><main className="login-form"><span className="eyebrow">MEMBER ACCESS</span><h1>登录</h1><p className="muted">使用管理员提供的账号访问系统。</p><form onSubmit={e=>{e.preventDefault();setLoggedIn(true);notify('已进入演示工作台');}}><label>账号<input name="username" autoComplete="username" placeholder="输入账号" required/></label><label>密码<input name="password" autoComplete="current-password" type="password" placeholder="输入密码" required/></label><Button type="submit" variant="primary">登录<Icon name="arrow"/></Button></form><p className="prototype-note">前端原型 · 虚构数据<br/>输入任意非空演示账号与密码即可查看。</p></main><div className="login-bottom">康米巨星猎头系统<span>前端原型 / 2026</span></div></div>;

 return <div className={`app ${detailVisible?'has-detail':''} ${detailWide?'expanded-detail':''}`}>
  <header className="mobile-header"><button aria-label="打开导航" className="icon-button" onClick={()=>setMobileNav(true)}><Icon name="menu"/></button><Mark/><span>康米巨星</span><small>原型</small></header>
  {mobileNav&&<button className="nav-scrim" aria-label="关闭导航" onClick={()=>setMobileNav(false)}/>}
  <aside className={`sidebar ${mobileNav?'open':''}`}>
   <a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('person');}}><Mark/><span>康米巨星<small>猎头系统</small></span></a>
   <nav aria-label="主要导航">{navItems.map(([key,icon,label])=><button key={key} className={`nav-item ${page===key?'active':''}`} onClick={()=>navigate(key)}><Icon name={icon}/><span>{label}</span>{key==='unread'&&unread.length>0&&<span className="nav-count">{unread.length}</span>}</button>)}</nav>
   <div className="sidebar-bottom"><nav aria-label="工具与管理"><button className={`nav-item ${page==='agent'?'active':''}`} onClick={()=>navigate('agent')}><Icon name="agent"/><span>Agent 接入</span></button>{actor.role==='admin'&&<button className={`nav-item ${page==='accounts'?'active':''}`} onClick={()=>navigate('accounts')}><Icon name="settings"/><span>账号管理</span></button>}</nav><button className="current-member" onClick={()=>setDialog({type:'profile'})}><span>{actor.name}<small>{actor.role==='admin'?'管理员':'普通成员'}</small></span><Icon name="more"/></button><div className="prototype-label"><span className="live-dot"/>前端原型 · 虚构数据</div></div>
  </aside>
  <main className={`main-panel ${['accounts','agent'].includes(page)?'full-page':''}`}>
   <header className="page-head"><div className="page-heading"><span className="eyebrow">{page==='person'?'01 / PEOPLE':page==='org'?'02 / ORGANIZATIONS':page==='unread'?'03 / UPDATES':page==='accounts'?'MEMBERS':'AGENT ACCESS'}</span><h1>{names[page]}{['person','org'].includes(page)&&<span className="count">{entities.filter(e=>e.type===page).length.toString().padStart(2,'0')}</span>}</h1></div>{['person','org'].includes(page)&&<Button icon="plus" variant="primary" onClick={()=>setDialog({type:'entity-new'})}>新建{names[page]}</Button>}{page==='accounts'&&<Button icon="plus" variant="primary" onClick={()=>setDialog({type:'member-new'})}>新建账号</Button>}{page==='unread'&&unread.length>0&&<Button variant="quiet" icon="check" onClick={()=>{setEntities(p=>p.map(e=>({...e,unread:false})));notify('全部更新已标为已读');}}>全部已读</Button>}</header>
   {['person','org'].includes(page)&&<><section className="list-toolbar"><div className="search-field"><Icon name="search"/><input aria-label="搜索档案" placeholder="搜索名称、昵称或观察记录" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<IconButton name="close" label="清空搜索" onClick={()=>setSearch('')}/>}</div><div className="filter-row"><select aria-label="筛选业务状态" value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="all">全部状态</option>{states.map(s=><option key={s}>{s}</option>)}</select><select aria-label="筛选负责人" value={ownerFilter} onChange={e=>setOwnerFilter(e.target.value)}><option value="all">全部负责人</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select aria-label="筛选开启关闭" value={lifeFilter} onChange={e=>setLifeFilter(e.target.value)}><option value="open">开启中</option><option value="closed">已关闭</option><option value="all">全部档案</option></select></div><div className="list-caption"><span>{filtered.length} 个档案</span><span>最近更新 <span aria-hidden="true">↓</span></span></div></section><div className="entity-list">{filtered.length?filtered.map(e=>{const latest=e.records.find(r=>!r.deleted);return <button key={e.id} className={`entity-row ${selected===e.id?'selected':''}`} onClick={()=>pick(e.id)}><div className="row-title"><h2>{e.name}</h2>{e.alias&&<span className="alias">{e.alias}</span>}{e.unread&&<span className="unread-dot" aria-label="有未读更新"/>}</div><div className="row-meta"><StateTag state={e.state}/>{ownerStates(e.type).includes(e.state)&&<span className="owner-names">{(e.owners[e.state]??[]).map(memberName).join('、')||'暂无负责人'}</span>}</div><p className="record-excerpt">{latest?.body??'尚无观察记录'}</p><div className="row-foot"><span>{latest?memberName(latest.author):'—'}<i>·</i>{e.updated}</span><span>{e.records.filter(r=>!r.deleted).length} 条记录 <Icon name="arrow" size={12}/></span></div></button>}):<Empty title="没有符合条件的档案" action={<Button variant="quiet" onClick={()=>{setSearch('');setStateFilter('all');setLifeFilter('all');setOwnerFilter('all');}}>清除筛选</Button>}>试试其他关键词，或调整筛选条件。</Empty>}</div></>}
   {page==='unread'&&<section className="updates-list">{unread.length?<><p className="section-description">其他成员带来的新内容，逐项查看后标记已读。</p>{unread.map(e=><div className="update-row" key={e.id}><span className="unread-dot"/><button className="update-target" onClick={()=>pick(e.id)}><div><span className="kind-label">{e.type==='person'?'人物':'组织'}</span><strong>{e.name}</strong></div><p>{e.records.find(r=>!r.deleted)?.body}</p><small>{e.updated}</small></button><IconButton name="check" label={`将${e.name}标记为已读`} onClick={()=>readEntity(e.id)}/></div>)}</>:<Empty title="已看完所有更新">新的观察记录和资料变化会出现在这里。</Empty>}</section>}
   {page==='accounts'&&<section className="accounts-content"><p className="section-description">管理内部成员的访问资格与账号权限。</p><div className="table-wrap"><table><thead><tr><th>成员</th><th>账号</th><th>角色</th><th>状态</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><strong>{m.name}</strong>{m.id===currentUser&&<small className="self-label">你</small>}</td><td className="muted mono">{m.username}</td><td>{m.role==='admin'?'管理员':'普通成员'}</td><td><span className={`account-state ${m.frozen?'frozen':''}`}><i/>{m.frozen?'已冻结':'正常'}</span></td><td><Button variant="quiet" onClick={()=>setDialog({type:'member-edit',member:m})}>管理<Icon name="arrow" size={14}/></Button></td></tr>)}</tbody></table></div><div className="note-block"><Icon name="lock"/><p>冻结账号后，该成员将无法继续访问。已有的观察记录与作者归属会保留。</p></div></section>}
   {page==='agent'&&<section className="agent-content"><div className="agent-intro"><div><h2>让 Agent 加入你的工作流</h2><p>通过 MCP 查询档案、整理材料、提交图文观察。<br/>每次操作都使用你的成员身份与权限。</p></div><div className="agent-symbol" aria-hidden="true"><Mark/><span/><i/></div></div><div className="agent-section"><span className="step-number">01</span><div><h3>创建个人凭证</h3><p>凭证用于识别你的账号，可随时撤销。</p><Button variant="outline" onClick={()=>notify('这是界面原型，正式服务接入后可创建凭证。')}>创建凭证<Icon name="plus" size={16}/></Button></div></div><div className="agent-section"><span className="step-number">02</span><div><h3>配置 Codex</h3><p>将服务地址与个人凭证配置到你的客户端。</p><div className="code-panel"><span className="code-label">MCP 配置示例</span><pre>{'[mcp_servers.talent_scout]\nurl = "{{MCP_SERVER_URL}}"\nbearer_token_env_var = "CTS_MCP_TOKEN"'}</pre></div></div></div><div className="agent-section"><span className="step-number">03</span><div><h3>复制使用说明</h3><p>帮助 Agent 理解档案、观察记录与协作规则。</p><Button variant="primary" icon="copy" onClick={async()=>{try{await navigator.clipboard.writeText('康米巨星猎头系统使用说明（前端原型）\n先确认成员身份；创建前检索档案；业务状态没有先后顺序；关闭后须重新开启才能修改；观察记录仅作者或管理员可编辑、删除和恢复；图片须先上传后引用附件标识。\n实际 MCP 地址与个人凭证待正式服务提供。');notify('使用说明已复制');}catch{notify('浏览器未允许复制，请使用正式接入页说明。');}}}>复制 Agent 使用说明</Button></div></div></section>}
  </main>
  {detailVisible&&<aside className="detail-panel" aria-label={`${entity.name}档案详情`}>
   <div className="detail-top"><span className="eyebrow">{entity.type==='person'?'人物':'组织'}档案</span><div>{entity.unread&&<Button variant="quiet small" icon="check" onClick={()=>readEntity(entity.id)}>标为已读</Button>}<IconButton name="expand" label={detailWide?'收起阅读视图':'展开阅读视图'} onClick={()=>setDetailWide(!detailWide)}/><IconButton name="close" label="关闭档案详情" onClick={()=>{setSelected(null);setDetailWide(false);}}/></div></div>
   <div className="detail-scroll" key={entity.id}><header className="entity-header"><div className="entity-name-line"><div><h1>{entity.name}</h1>{entity.alias&&<span className="detail-alias">{entity.alias}</span>}</div>{locked?<StateTag state={entity.state}/>:<select className="state-select" aria-label="变更业务状态" value={entity.state} onChange={e=>changeState(e.target.value)}>{(entity.type==='person'?personStates:orgStates).map(s=><option key={s}>{s}</option>)}</select>}</div><p className="entity-intro">{entity.intro||'尚未填写简介'}</p><dl className="metadata">{ownerStates(entity.type).includes(entity.state)&&<><dt>{ownerLabel(entity.state)}</dt><dd>{(entity.owners[entity.state]??[]).map(memberName).join(' · ')||'暂未分配'}</dd></>}{entity.contacts.map((c,i)=><React.Fragment key={i}><dt>{c.type}</dt><dd>{c.value}</dd></React.Fragment>)}</dl><div className="entity-actions">{locked?<Button variant="outline small" onClick={()=>setDialog({type:'reopen'})} icon="history">重新开启</Button>:<><Button variant="quiet small" icon="edit" onClick={()=>setDialog({type:'entity-edit',entity})}>编辑资料</Button><Button variant="quiet small" icon="lock" onClick={()=>setDialog({type:'close-entity'})}>关闭档案</Button></>}</div></header>
   {locked&&<div className="locked-notice"><Icon name="lock" size={16}/><span>档案已关闭，重新开启后可继续维护。</span></div>}
   <div className="timeline-tabs" role="tablist" aria-label="动态筛选">{[['all','全部动态'],['records','仅观察记录'],['deleted','已删除']].map(([key,label])=><button role="tab" aria-selected={recordView===key} key={key} className={recordView===key?'active':''} onClick={()=>setRecordView(key)}>{label}{key==='deleted'&&entity.records.some(r=>r.deleted)&&<small>{entity.records.filter(r=>r.deleted).length}</small>}</button>)}</div>
   {!locked&&recordView!=='deleted'&&<div className={`composer ${composeOpen?'is-open':'is-collapsed'}`}><textarea ref={composerText} onFocus={()=>setComposeOpen(true)} aria-label="新的观察记录" placeholder="写下新的观察…" value={text} onChange={e=>setText(e.target.value)} rows={composeOpen?3:1}/>{!composeOpen&&<button className="compose-launch" aria-label="开始撰写观察" onClick={()=>{setComposeOpen(true);composerText.current?.focus();}}><Icon name="plus" size={17}/></button>}{images.length>0&&<div className="composer-images">{images.map((im,i)=><div key={im.url}><img src={im.url} alt={im.name}/><button aria-label={`移除图片${i+1}`} onClick={()=>setImages(p=>p.filter((_,n)=>n!==i))}><Icon name="close" size={12}/></button></div>)}</div>}<div className="composer-foot"><input ref={inputFile} type="file" accept="image/*" multiple hidden onChange={e=>{const files=[...e.target.files].filter(f=>f.type.startsWith('image/'));setImages(p=>[...p,...files.map(f=>({url:URL.createObjectURL(f),name:f.name}))]);e.target.value='';}}/><button className="add-image" onClick={()=>inputFile.current?.click()}><Icon name="image"/><span>添加图片</span></button><Button variant="primary small" disabled={!text.trim()&&!images.length} onClick={publish}>发布记录</Button></div></div>}
   <section className="timeline">{entity.records.filter(r=>recordView==='deleted'?r.deleted:!r.deleted).length===0&&<Empty title={recordView==='deleted'?'暂无已删除记录':'尚无观察记录'}>{recordView==='deleted'?'删除的记录会保留在这里，可以按权限恢复。':'写下第一条观察，开始积累对这个对象的了解。'}</Empty>}{[...entity.records.filter(r=>recordView==='deleted'?r.deleted:!r.deleted),...(recordView==='all'?entity.events:[])].sort((a,b)=>timelineOrder(b)-timelineOrder(a)).map(r=>r.kind==='system'?<div className="system-event" key={r.id}><span className="event-node"/><span>{memberName(r.actor)}{r.text}<time>{r.time}</time></span></div>:<React.Fragment key={r.id}><article className={`observation ${r.deleted?'deleted':''}`}><div className="record-byline"><strong>{memberName(r.author)}</strong><time>{r.time}</time>{r.edited&&<span className="edited-label">已编辑</span>}<div className="byline-spacer"/><IconButton name="history" label={`查看${memberName(r.author)}记录的历史`} onClick={()=>setDialog({type:'history',record:r})}/></div><div className="record-body">{r.body.split('\n').map((line,n)=>line?<p key={n}>{line}</p>:null)}</div>{r.images.length>0&&<div className="record-images">{r.images.map(im=><button key={im.url} onClick={()=>setDialog({type:'image',image:im})}><img src={im.url} alt={im.name}/></button>)}</div>}{!locked&&(r.author===currentUser||actor.role==='admin')&&<div className="record-actions">{r.deleted?<button onClick={()=>recordAction(r,'恢复')}><Icon name="history" size={13}/>恢复记录</button>:<><button onClick={()=>setDialog({type:'record-edit',record:r})}>编辑</button><button onClick={()=>setDialog({type:'record-delete',record:r})}>删除</button></>}</div>}</article></React.Fragment>)}</section>
   </div>
  </aside>}
  {toast&&<div className="toast" role="status"><Icon name="check" size={16}/>{toast}</div>}
  {dialog&&<Modal title={{'entity-new':`新建${names[page]}`,'entity-edit':'编辑档案资料','record-edit':'编辑观察记录','record-delete':'删除观察记录','history':'记录历史','reopen':'重新开启档案','close-entity':'关闭档案','member-new':'新建账号','member-edit':'管理账号','profile':'个人账号','image':'图片预览'}[dialog.type]} onClose={dialogClose} wide={['history','image'].includes(dialog.type)}>
   {['entity-new','entity-edit'].includes(dialog.type)&&<form className="modal-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);if(!f.get('name').trim()){notify('名称不能为空');return;}const contacts=f.getAll('contact-type').map((type,i)=>({type,value:f.getAll('contact-value')[i].trim()})).filter(c=>c.value);if(dialog.type==='entity-edit'&&entity.name===f.get('name').trim()&&entity.alias===f.get('alias').trim()&&entity.intro===f.get('intro').trim()&&JSON.stringify(contacts)===JSON.stringify(entity.contacts.map(({type,value})=>({type,value})))&&ownerStates(entity.type).every(state=>JSON.stringify(f.getAll('owners:'+state))===JSON.stringify(entity.owners[state]??[]))){dialogClose();notify('内容没有变化');return;}if(dialog.type==='entity-new'){const id=uuid();setEntities(prev=>[{id,type:page,name:f.get('name').trim(),alias:f.get('alias').trim(),intro:f.get('intro').trim(),state:'视奸观察',owners:{},contacts,updated:'刚刚',unread:false,records:[],events:[]},...prev]);pick(id);notify('档案已创建');}else{mutate(entity.id,d=>{d.name=f.get('name').trim();d.alias=f.get('alias').trim();d.intro=f.get('intro').trim();d.contacts=contacts;for(const state of ownerStates(d.type))d.owners[state]=f.getAll('owners:'+state);return addEvent(d,'更新了档案资料');},'资料已保存');}dialogClose();}}><label>{(dialog.entity?.type??page)==='org'?'组织名称':'昵称 / 显示名称'}<input name="name" defaultValue={dialog.entity?.name??''} required maxLength={80} autoFocus/></label><label>别名<input name="alias" defaultValue={dialog.entity?.alias??''} maxLength={80}/></label><label>简介<textarea name="intro" rows={4} defaultValue={dialog.entity?.intro??''}/></label><ContactFields initial={dialog.entity?.contacts??[]}/>{dialog.type==='entity-edit'&&<details className="owners-editor" open><summary>状态负责人</summary>{ownerStates(entity.type).map(state=><fieldset key={state}><legend>{state}</legend><div className="checkbox-group">{members.filter(m=>!m.frozen||(entity.owners[state]??[]).includes(m.id)).map(m=><label key={m.id}><input type="checkbox" name={'owners:'+state} value={m.id} defaultChecked={(entity.owners[state]??[]).includes(m.id)}/>{m.name}{m.frozen?'（已冻结）':''}</label>)}</div></fieldset>)}</details>}<div className="modal-actions"><Button type="button" variant="quiet" onClick={dialogClose}>取消</Button><Button variant="primary" type="submit">{dialog.type==='entity-new'?'创建档案':'保存修改'}</Button></div></form>}
   {dialog.type==='record-edit'&&<form className="modal-form" onSubmit={e=>{e.preventDefault();const body=new FormData(e.target).get('body').trim();if(!body&&!dialog.record.images.length)return;recordAction(dialog.record,'编辑',body);}}><p className="muted">原始作者：{memberName(dialog.record.author)}。修改后保留旧版本。</p><label>观察内容<textarea name="body" rows={9} defaultValue={dialog.record.body} autoFocus required={!dialog.record.images.length}/></label><div className="modal-actions"><Button type="button" variant="quiet" onClick={dialogClose}>取消</Button><Button type="submit" variant="primary">保存修改</Button></div></form>}
   {dialog.type==='record-delete'&&<div className="modal-form"><p>记录将从普通列表隐藏，内容、历史版本和关联图片仍然保留，可以恢复。</p><div className="modal-actions"><Button variant="quiet" onClick={dialogClose}>取消</Button><Button variant="primary" onClick={()=>recordAction(dialog.record,'删除')}>删除记录</Button></div></div>}
   {dialog.type==='history'&&<div className="history-list">{[...dialog.record.versions].reverse().map((v,i)=><article key={i}><div className="history-byline"><span>版本 {dialog.record.versions.length-i}</span><strong>{v.operation}</strong><time>{v.time}</time></div><small>{memberName(v.actor)}</small><p>{v.body||'（仅图片记录）'}</p>{v.images?.length>0&&<div className="history-images">{v.images.map(im=><a key={im.url} href={im.url} target="_blank" rel="noreferrer" aria-label={`打开历史图片：${im.name}`}><img src={im.url} alt={im.name}/></a>)}</div>}</article>)}</div>}
   {['reopen','close-entity'].includes(dialog.type)&&<form className="modal-form" onSubmit={e=>{e.preventDefault();changeState(new FormData(e.target).get('state'));dialogClose();}}><p>{dialog.type==='reopen'?'选择一个开启类业务状态，恢复对档案的维护。':'关闭后仍可阅读资料与历史，编辑前需要重新开启。'}</p><label>业务状态<select name="state" defaultValue={dialog.type==='reopen'?(entity.lastOpenState??'视奸观察'):'已弃用'}>{(entity.type==='person'?personStates:orgStates).filter(s=>dialog.type==='reopen'?!isClosed(s):isClosed(s)).map(s=><option key={s}>{s}</option>)}</select></label><div className="modal-actions"><Button variant="quiet" type="button" onClick={dialogClose}>取消</Button><Button variant="primary" type="submit">{dialog.type==='reopen'?'重新开启':'确认关闭'}</Button></div></form>}
   {['member-new','member-edit'].includes(dialog.type)&&<form className="modal-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);if(!f.get('name').trim()||!f.get('username').trim()){notify('名称和账号不能为空');return;}if(members.some(m=>m.id!==dialog.member?.id&&m.username===f.get('username').trim())){notify('账号已存在');return;}const role=f.get('role'),frozen=f.get('frozen')==='yes';if(dialog.member?.role==='admin'&&(frozen||role!=='admin')&&!members.some(m=>m.id!==dialog.member.id&&m.role==='admin'&&!m.frozen)){notify('须保留至少一名未冻结的管理员');return;}const next={id:dialog.member?.id??uuid(),name:f.get('name').trim(),username:f.get('username').trim(),role,frozen};setMembers(p=>dialog.member?p.map(m=>m.id===next.id?next:m):[...p,next]);if(next.id===currentUser){if(frozen)setLoggedIn(false);else if(role!=='admin')navigate('person');}dialogClose();notify('演示账号已保存');}}><label>显示名称<input name="name" defaultValue={dialog.member?.name??''} required/></label><label>账号<input name="username" defaultValue={dialog.member?.username??''} required/></label><label>角色<select name="role" defaultValue={dialog.member?.role??'member'}><option value="member">普通成员</option><option value="admin">管理员</option></select></label>{dialog.member&&<label>账号状态<select name="frozen" defaultValue={dialog.member.frozen?'yes':'no'}><option value="no">正常</option><option value="yes">已冻结</option></select></label>}<p className="field-hint">此处仅演示账号管理交互，不创建真实凭证。</p><div className="modal-actions"><Button type="button" variant="quiet" onClick={dialogClose}>取消</Button><Button type="submit" variant="primary">保存</Button></div></form>}
   {dialog.type==='profile'&&<div className="modal-form"><div className="profile-summary"><strong>{actor.name}</strong><span>{actor.username} · {actor.role==='admin'?'管理员':'普通成员'}</span></div><p className="muted">当前使用虚构成员账号预览页面。</p><Button variant="outline" icon="logout" onClick={()=>{setLoggedIn(false);dialogClose();}}>查看登录页</Button></div>}
   {dialog.type==='image'&&<div className="lightbox"><img src={dialog.image.url} alt={dialog.image.name}/></div>}
  </Modal>}
 </div>;
}
function ResponsivePreview(){return <main className="responsive-preview"><header><a href="/">← 桌面原型</a><span>窄屏预览 · 390 × 844</span></header><iframe src="/?frame=1" title="手机原型" width="390" height="844"/></main>;}
createRoot(document.getElementById('root')).render(new URLSearchParams(location.search).get('preview')==='mobile'?<ResponsivePreview/>:<App/>);
