import React,{useState,lazy,Suspense} from 'react';
import {MaterialList,MaterialEditForm,MaterialQuotaForm} from '../../../app/ui/Materials';
import {Modal} from '../../../app/ui/Modal';
const PdfPreview=lazy(()=>import('../../../app/ui/PdfPreview'));
const stores=new Map();
export function MaterialsPreview({entity,actor,locked,onCount}){
 const store=stores.get(entity.id)??{files:[],limit:entity.type==='person'?100000000:200000000};stores.set(entity.id,store);
 const[revision,refresh]=useState(0),[deleted,setDeleted]=useState(false),[dialog,setDialog]=useState(null),[error,setError]=useState('');
 const used=store.files.reduce((n,f)=>n+f.byte_size,0),capacity={used_bytes:used,reserved_bytes:0,limit_bytes:store.limit,available_bytes:store.limit-used,count:store.files.filter(f=>!f.deleted).length,version:revision+1,default_bytes:entity.type==='person'?100000000:200000000,max_file_bytes:100000000};
 const changed=()=>{refresh(n=>n+1);onCount(store.files.filter(f=>!f.deleted).length);setDialog(null);};
 function upload(files){setError('');for(const file of files){if(!file.size||file.size>100000000||file.size+store.files.reduce((n,f)=>n+f.byte_size,0)>store.limit){setError('文件超过单文件或档案容量限制');continue;}const id=crypto.randomUUID(),url=URL.createObjectURL(file);store.files.push({id,archive_id:entity.id,owner_id:actor.id,owner_name:actor.name,name:file.name,description:'',mime_type:file.type,byte_size:file.size,sha256:'',state:'ready',deleted:false,version:1,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),download_url:url,preview_url:/^(image\/(png|jpeg|webp|gif)|application\/pdf)$/.test(file.type)?url:null,reference_url:location.origin+location.pathname+'?archive='+entity.id+'&material='+id});}changed();}
 const open=(action,file)=>setDialog({action,file});
 return <><MaterialList items={store.files.filter(f=>f.deleted===deleted).map(f=>({...f,editable:!locked}))} capacity={capacity} deleted={deleted} onDeleted={setDeleted} onFiles={upload} onEdit={f=>open('edit',f)} onDelete={f=>open('delete',f)} onRestore={f=>open('restore',f)} onPurge={f=>open('purge',f)} onPreview={f=>open('preview',f)} onCopy={f=>navigator.clipboard?.writeText(f.reference_url)} onQuota={actor.role==='admin'?()=>open('quota'):undefined} locked={locked} loading={false} error={error} onRetry={()=>setError('')} onMore={()=>{}}/>
 {dialog&&<Modal title={dialog.action==='edit'?'名称与说明':dialog.action==='quota'?'调整材料容量':dialog.action==='preview'?dialog.file.name:dialog.action==='delete'?'删除材料':dialog.action==='restore'?'恢复材料':'彻底删除材料'} wide={dialog.action==='preview'} onClose={()=>setDialog(null)}><div className="live-modal-body">{dialog.action==='edit'?<MaterialEditForm file={dialog.file} busy={false} error="" onSubmit={(name,description)=>{Object.assign(store.files.find(f=>f.id===dialog.file.id),{name,description});changed();}} onCancel={()=>setDialog(null)} onReload={()=>{}}/>:dialog.action==='quota'?<MaterialQuotaForm capacity={capacity} busy={false} error="" onSubmit={bytes=>{store.limit=bytes;changed();}} onCancel={()=>setDialog(null)} onReload={()=>{}}/>:dialog.action==='preview'?dialog.file.mime_type==='application/pdf'?<Suspense fallback={<p>正在载入 PDF…</p>}><PdfPreview url={dialog.file.preview_url}/></Suspense>:<img src={dialog.file.preview_url} alt={dialog.file.name} className="material-preview"/>:<div className="material-form"><strong>{dialog.file.name}</strong><p>{dialog.action==='delete'?'删除后可在回收站恢复，文件仍占容量。':dialog.action==='restore'?'恢复后将重新出现在全部材料中。':'将永久清除这份在线材料，无法从回收站恢复。'}</p><div className="modal-actions"><button className="button quiet" onClick={()=>setDialog(null)}>取消</button><button className="button primary" onClick={()=>{const file=store.files.find(f=>f.id===dialog.file.id);if(dialog.action==='purge'){URL.revokeObjectURL(file.download_url);store.files=store.files.filter(f=>f!==file);}else file.deleted=dialog.action==='delete';changed();}}>确认{dialog.action==='delete'?'删除':dialog.action==='restore'?'恢复':'彻底删除'}</button></div></div>}</div></Modal>}</>;
}
